extern crate libc;
extern crate eo_sys;
extern crate eina_sys;

use libc::*;
use eo_sys::*;
use eina_sys::*;

/* automatically generated by rust-bindgen */

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EflGfxPathCommand {
    EflGfxPathCommandTypeEnd = 0,
    EflGfxPathCommandTypeMoveTo = 1,
    EflGfxPathCommandTypeLineTo = 2,
    EflGfxPathCommandTypeCubicTo = 3,
    EflGfxPathCommandTypeClose = 4,
    EflGfxPathCommandTypeLast = 5,
}

#[repr(C)]
pub struct EflGfxDash {
    pub length: c_double,
    pub gap: c_double,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EflGfxCap {
    EflGfxCapButt = 0,
    EflGfxCapRound = 1,
    EflGfxCapSquare = 2,
    EflGfxCapLast = 3,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EflGfxJoin {
    EflGfxJoinMiter = 0,
    EflGfxJoinRound = 1,
    EflGfxJoinBevel = 2,
    EflGfxJoinLast = 3,
}

#[repr(C)]
pub struct EflGfxGradientStop {
    pub offset: c_double,
    pub r: c_int,
    pub g: c_int,
    pub b: c_int,
    pub a: c_int,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EflGfxGradientSpread {
    EflGfxGradientSpreadPad = 0,
    EflGfxGradientSpreadReflect = 1,
    EflGfxGradientSpreadRepeat = 2,
    EflGfxGradientSpreadLast = 3,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EflGfxFillSpread {
    EflGfxFillReflect = 0,
    EflGfxFillRepeat = 1,
    EflGfxFillRestrict = 2,
    EflGfxFillRestrictReflect = 3,
    EflGfxFillRestrictRepeat = 4,
    EflGfxFillPad = 5,
}

#[repr(C)]
pub struct EflModelChildrenEvent {
    pub child: *mut Eo,
    pub index: c_uint,
}

pub type EflControl = Eo;
pub type EflFile = Eo;
pub type EflImage = Eo;
pub type EflPlayer = Eo;
pub type EflText = Eo;
pub type EflTextProperties = Eo;
pub type EflFontSize = c_int;
pub type EflModelBase = Eo;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EflModelLoadStatus {
    EflModelLoadStatusError = 0,
    EflModelLoadStatusLoadingProperties = 1,
    EflModelLoadStatusLoadingChildren = 2,
    EflModelLoadStatusLoading = 3,
    EflModelLoadStatusLoadedProperties = 4,
    EflModelLoadStatusLoadedChildren = 8,
    EflModelLoadStatusLoaded = 12,
    EflModelLoadStatusUnloading = 16,
    EflModelLoadStatusUnloaded = 32,
}

#[repr(C)]
pub struct EflModelPropertyEvent {
    pub changed_properties: *mut EinaArray,
    pub invalidated_properties: *mut EinaArray,
}

#[repr(C)]
pub struct EflModelLoad {
    pub status: EflModelLoadStatus,
}

pub type EflGfxBase = Eo;
pub type EflGfxStack = Eo;
pub type EflGfxFill = Eo;
pub type EflGfxView = Eo;
pub type EflGfxShape = Eo;
pub type EflGfxGradientBase = Eo;
pub type EflGfxGradientLinear = Eo;
pub type EflGfxGradientRadial = Eo;
pub type EflGfxFilter = Eo;

#[link(name = "efl")]
extern "C" {
    pub static _EFL_FILE_EVENT_ASYNC_OPENED: EoEventDescription;
    pub static _EFL_FILE_EVENT_ASYNC_ERROR: EoEventDescription;
    pub static _EFL_MODEL_BASE_EVENT_LOAD_STATUS: EoEventDescription;
    pub static _EFL_MODEL_BASE_EVENT_PROPERTIES_CHANGED: EoEventDescription;
    pub static _EFL_MODEL_BASE_EVENT_CHILD_ADDED: EoEventDescription;
    pub static _EFL_MODEL_BASE_EVENT_CHILD_REMOVED: EoEventDescription;
    pub static _EFL_MODEL_BASE_EVENT_CHILDREN_COUNT_CHANGED:
               EoEventDescription;
    pub static _EFL_GFX_CHANGED: EoEventDescription;
    pub static _EFL_GFX_PATH_CHANGED: EoEventDescription;
}
#[link(name = "efl")]
extern "C" {
    pub fn efl_control_interface_get() -> *const EoClass;
    pub fn efl_control_priority_set(priority: c_int);
    pub fn efl_control_priority_get() -> c_int;
    pub fn efl_control_suspend_set(suspend: EinaBool);
    pub fn efl_control_suspend_get() -> EinaBool;
    pub fn efl_file_interface_get() -> *const EoClass;
    pub fn efl_file_mmap_set(f: *const EinaFile,
                             key: *const c_char) -> EinaBool;
    pub fn efl_file_mmap_get(f: *mut *const EinaFile,
                             key: *mut *const c_char);
    pub fn efl_file_set(file: *const c_char,
                        key: *const c_char) -> EinaBool;
    pub fn efl_file_get(file: *mut *const c_char,
                        key: *mut *const c_char);
    pub fn efl_file_async_set(async: EinaBool);
    pub fn efl_file_async_get() -> EinaBool;
    pub fn efl_file_save(file: *const c_char,
                         key: *const c_char,
                         flags: *const c_char) -> EinaBool;
    pub fn efl_file_eject();
    pub fn efl_file_async_wait() -> EinaBool;
    pub fn efl_image_interface_get() -> *const EoClass;
    pub fn efl_image_animated_get() -> EinaBool;
    pub fn efl_image_load_size_set(w: c_int,
                                   h: c_int);
    pub fn efl_image_load_size_get(w: *mut c_int,
                                   h: *mut c_int);
    pub fn efl_image_smooth_scale_set(smooth_scale: EinaBool);
    pub fn efl_image_smooth_scale_get() -> EinaBool;
    pub fn efl_image_ratio_get() -> c_double;
    pub fn efl_player_interface_get() -> *const EoClass;
    pub fn efl_player_playable_get() -> EinaBool;
    pub fn efl_player_play_set(play: EinaBool);
    pub fn efl_player_play_get() -> EinaBool;
    pub fn efl_player_position_set(sec: c_double);
    pub fn efl_player_position_get() -> c_double;
    pub fn efl_player_progress_get() -> c_double;
    pub fn efl_player_play_speed_set(speed: c_double);
    pub fn efl_player_play_speed_get() -> c_double;
    pub fn efl_player_audio_volume_set(volume: c_double);
    pub fn efl_player_audio_volume_get() -> c_double;
    pub fn efl_player_audio_mute_set(mute: EinaBool);
    pub fn efl_player_audio_mute_get() -> EinaBool;
    pub fn efl_player_length_get() -> c_double;
    pub fn efl_player_seekable_get() -> EinaBool;
    pub fn efl_text_interface_get() -> *const EoClass;
    pub fn efl_text_set(text: *const c_char);
    pub fn efl_text_get() -> *const c_char;
    pub fn efl_text_properties_interface_get() -> *const EoClass;
    pub fn efl_text_properties_font_set(font: *const c_char,
                                        size: EflFontSize);
    pub fn efl_text_properties_font_get(font: *mut *const c_char,
                                        size: *mut EflFontSize);
    pub fn efl_text_properties_font_source_set(font_source: *const c_char);
    pub fn efl_text_properties_font_source_get() -> *const c_char;
    pub fn efl_model_base_interface_get() -> *const EoClass;
    pub fn efl_model_load_status_get() -> EflModelLoadStatus;
    pub fn efl_model_properties_get(properties: *const *mut EinaArray)
     -> EflModelLoadStatus;
    pub fn efl_model_property_set(property: *const c_char,
                                  value: *const EinaValue)
     -> EflModelLoadStatus;
    pub fn efl_model_property_get(property: *const c_char,
                                  value: *mut *const EinaValue)
     -> EflModelLoadStatus;
    pub fn efl_model_children_slice_get(start: c_uint,
                                        count: c_uint,
                                        children_accessor:
                                            *mut *mut EinaAccessor)
     -> EflModelLoadStatus;
    pub fn efl_model_children_count_get(children_count: *mut c_uint)
     -> EflModelLoadStatus;
    pub fn efl_model_load();
    pub fn efl_model_unload();
    pub fn efl_model_properties_load();
    pub fn efl_model_children_load();
    pub fn efl_model_child_add() -> *mut EoBase;
    pub fn efl_model_child_del(child: *mut EoBase) -> EflModelLoadStatus;
    pub fn efl_gfx_base_interface_get() -> *const EoClass;
    pub fn efl_gfx_position_set(x: c_int,
                                y: c_int);
    pub fn efl_gfx_position_get(x: *mut c_int,
                                y: *mut c_int);
    pub fn efl_gfx_size_set(w: c_int,
                            h: c_int);
    pub fn efl_gfx_size_get(w: *mut c_int,
                            h: *mut c_int);
    pub fn efl_gfx_color_set(r: c_int,
                             g: c_int,
                             b: c_int,
                             a: c_int);
    pub fn efl_gfx_color_get(r: *mut c_int,
                             g: *mut c_int,
                             b: *mut c_int,
                             a: *mut c_int);
    pub fn efl_gfx_color_part_set(part: *const c_char,
                                  r: c_int,
                                  g: c_int,
                                  b: c_int,
                                  a: c_int) -> EinaBool;
    pub fn efl_gfx_color_part_get(part: *const c_char,
                                  r: *mut c_int,
                                  g: *mut c_int,
                                  b: *mut c_int,
                                  a: *mut c_int) -> EinaBool;
    pub fn efl_gfx_visible_set(v: EinaBool);
    pub fn efl_gfx_visible_get() -> EinaBool;
    pub fn efl_gfx_stack_interface_get() -> *const EoClass;
    pub fn efl_gfx_stack_layer_set(l: c_short);
    pub fn efl_gfx_stack_layer_get() -> c_short;
    pub fn efl_gfx_stack_below_get() -> *mut EflGfxStack;
    pub fn efl_gfx_stack_above_get() -> *mut EflGfxStack;
    pub fn efl_gfx_stack_below(below: *mut EflGfxStack);
    pub fn efl_gfx_stack_raise();
    pub fn efl_gfx_stack_above(above: *mut EflGfxStack);
    pub fn efl_gfx_stack_lower();
    pub fn efl_gfx_fill_interface_get() -> *const EoClass;
    pub fn efl_gfx_fill_spread_set(spread: EflGfxFillSpread);
    pub fn efl_gfx_fill_spread_get() -> EflGfxFillSpread;
    pub fn efl_gfx_fill_set(x: c_int,
                            y: c_int,
                            w: c_int,
                            h: c_int);
    pub fn efl_gfx_fill_get(x: *mut c_int,
                            y: *mut c_int,
                            w: *mut c_int,
                            h: *mut c_int);
    pub fn efl_gfx_view_interface_get() -> *const EoClass;
    pub fn efl_gfx_view_size_set(w: c_int,
                                 h: c_int);
    pub fn efl_gfx_view_size_get(w: *mut c_int,
                                 h: *mut c_int);
    pub fn efl_gfx_shape_mixin_get() -> *const EoClass;
    pub fn efl_gfx_shape_stroke_scale_get() -> c_double;
    pub fn efl_gfx_shape_stroke_scale_set(s: c_double);
    pub fn efl_gfx_shape_stroke_color_get(r: *mut c_int,
                                          g: *mut c_int,
                                          b: *mut c_int,
                                          a: *mut c_int);
    pub fn efl_gfx_shape_stroke_color_set(r: c_int,
                                          g: c_int,
                                          b: c_int,
                                          a: c_int);
    pub fn efl_gfx_shape_stroke_width_get() -> c_double;
    pub fn efl_gfx_shape_stroke_width_set(w: c_double);
    pub fn efl_gfx_shape_stroke_location_get() -> c_double;
    pub fn efl_gfx_shape_stroke_location_set(centered: c_double);
    pub fn efl_gfx_shape_stroke_dash_get(dash: *mut *const EflGfxDash,
                                         length: *mut c_uint);
    pub fn efl_gfx_shape_stroke_dash_set(dash: *const EflGfxDash,
                                         length: c_uint);
    pub fn efl_gfx_shape_stroke_cap_get() -> EflGfxCap;
    pub fn efl_gfx_shape_stroke_cap_set(c: EflGfxCap);
    pub fn efl_gfx_shape_stroke_join_get() -> EflGfxJoin;
    pub fn efl_gfx_shape_stroke_join_set(j: EflGfxJoin);
    pub fn efl_gfx_shape_path_set(op: *const EflGfxPathCommand,
                                  points: *const c_double);
    pub fn efl_gfx_shape_path_get(op: *mut *const EflGfxPathCommand,
                                  points: *mut *const c_double);
    pub fn efl_gfx_shape_path_length_get(commands: *mut c_uint,
                                         points: *mut c_uint);
    pub fn efl_gfx_shape_current_get(x: *mut c_double,
                                     y: *mut c_double);
    pub fn efl_gfx_shape_current_ctrl_get(x: *mut c_double,
                                          y: *mut c_double);
    pub fn efl_gfx_shape_dup(dup_from: *const EoBase);
    pub fn efl_gfx_shape_bounds_get(r: *mut EinaRectangle);
    pub fn efl_gfx_shape_reset();
    pub fn efl_gfx_shape_append_move_to(x: c_double,
                                        y: c_double);
    pub fn efl_gfx_shape_append_line_to(x: c_double,
                                        y: c_double);
    pub fn efl_gfx_shape_append_quadratic_to(x: c_double,
                                             y: c_double,
                                             ctrl_x: c_double,
                                             ctrl_y: c_double);
    pub fn efl_gfx_shape_append_squadratic_to(x: c_double,
                                              y: c_double);
    pub fn efl_gfx_shape_append_cubic_to(x: c_double,
                                         y: c_double,
                                         ctrl_x0: c_double,
                                         ctrl_y0: c_double,
                                         ctrl_x1: c_double,
                                         ctrl_y1: c_double);
    pub fn efl_gfx_shape_append_scubic_to(x: c_double,
                                          y: c_double,
                                          ctrl_x: c_double,
                                          ctrl_y: c_double);
    pub fn efl_gfx_shape_append_arc_to(x: c_double,
                                       y: c_double,
                                       rx: c_double,
                                       ry: c_double,
                                       angle: c_double,
                                       large_arc: EinaBool,
                                       sweep: EinaBool);
    pub fn efl_gfx_shape_append_close();
    pub fn efl_gfx_shape_append_circle(x: c_double,
                                       y: c_double,
                                       radius: c_double);
    pub fn efl_gfx_shape_append_rect(x: c_double,
                                     y: c_double,
                                     w: c_double,
                                     h: c_double,
                                     rx: c_double,
                                     ry: c_double);
    pub fn efl_gfx_shape_append_svg_path(svg_path_data: *const c_char);
    pub fn efl_gfx_shape_interpolate(from: *const EoBase, to: *const EoBase,
                                     pos_map: c_double)
     -> EinaBool;
    pub fn efl_gfx_shape_equal_commands(with: *const EoBase) -> EinaBool;
    pub fn efl_gfx_gradient_base_interface_get() -> *const EoClass;
    pub fn efl_gfx_gradient_stop_set(colors: *const EflGfxGradientStop,
                                     length: c_uint);
    pub fn efl_gfx_gradient_stop_get(colors: *mut *const EflGfxGradientStop,
                                     length: *mut c_uint);
    pub fn efl_gfx_gradient_spread_set(s: EflGfxGradientSpread);
    pub fn efl_gfx_gradient_spread_get() -> EflGfxGradientSpread;
    pub fn efl_gfx_gradient_linear_interface_get() -> *const EoClass;
    pub fn efl_gfx_gradient_linear_start_set(x: c_double,
                                             y: c_double);
    pub fn efl_gfx_gradient_linear_start_get(x: *mut c_double,
                                             y: *mut c_double);
    pub fn efl_gfx_gradient_linear_end_set(x: c_double,
                                           y: c_double);
    pub fn efl_gfx_gradient_linear_end_get(x: *mut c_double,
                                           y: *mut c_double);
    pub fn efl_gfx_gradient_radial_interface_get() -> *const EoClass;
    pub fn efl_gfx_gradient_radial_center_set(x: c_double,
                                              y: c_double);
    pub fn efl_gfx_gradient_radial_center_get(x: *mut c_double,
                                              y: *mut c_double);
    pub fn efl_gfx_gradient_radial_radius_set(r: c_double);
    pub fn efl_gfx_gradient_radial_radius_get() -> c_double;
    pub fn efl_gfx_gradient_radial_focal_set(x: c_double,
                                             y: c_double);
    pub fn efl_gfx_gradient_radial_focal_get(x: *mut c_double,
                                             y: *mut c_double);
    pub fn efl_gfx_filter_interface_get() -> *const EoClass;
}
