[package]
name = "eina"
version = "0.1.0"
authors = ["Nigel Tan <ntan2@gmail.com>"]

[dependencies]
libc = "0.2"

[dependencies.eina-sys]
git = "https://github.com/ntan15/rust-efl"
version = "0.1.0"

