[package]
name = "efreet-trash-sys"
version = "0.1.0"
authors = ["Nigel Tan <ntan2@gmail.com>"]

[dependencies]
libc = "0.2"

[dependencies.efreet-sys]
path = "../efreet-sys"
version = "0.1.0"

[dependencies.eina-sys]
path = "../eina-sys"
version = "0.1.0"
