#![allow(non_camel_case_types)]
extern crate libc;
extern crate eina_sys;
extern crate eet_sys;

use libc::*;
use eina_sys::*;
use eet_sys::*;
/* automatically generated by rust-bindgen */

#[repr(C)]
pub struct Eio_Version {
    pub major: c_int,
    pub minor: c_int,
    pub micro: c_int,
    pub revision: c_int,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EioFileOp {
    EioFileCopy = 0,
    EioFileMove = 1,
    EioDirCopy = 2,
    EioDirMove = 3,
    EioUnlink = 4,
    EioFileGetpwnam = 5,
    EioFileGetgrnam = 6,
}
pub enum Eio_File { }
pub type EioFilterCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                   handler: *mut Eio_File,
                                                   file: *const c_char)
                              -> EinaBool>;
pub type EioMainCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                 handler: *mut Eio_File,
                                                 file: *const c_char)>;
pub type EioFilterDirectCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                         handler: *mut Eio_File,
                                                         info: *const Eina_File_Direct_Info)
                              -> EinaBool>;
pub type EioFilterDirCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                      handler: *mut Eio_File,
                                                      info: *mut Eina_File_Direct_Info)
                              -> EinaBool>;
pub type EioMainDirectCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                       handler: *mut Eio_File,
                                                       info: *const Eina_File_Direct_Info)>;
pub type EioStatCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                 handler: *mut Eio_File,
                                                 stat: *const Eina_Stat)>;
pub type EioProgressCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                     handler: *mut Eio_File,
                                                     info: *const Eio_Progress)>;
pub type EioEetOpenCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                    handler: *mut Eio_File,
                                                    file: *mut Eet_File)>;
pub type EioOpenCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                 handler: *mut Eio_File,
                                                 file: *mut Eina_File)>;
pub type EioFilterMapCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                      handler: *mut Eio_File,
                                                      map: *mut c_void,
                                                      length: size_t) -> EinaBool>;
pub type EioMapCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                handler: *mut Eio_File,
                                                map: *mut c_void,
                                                length: size_t)>;
pub type EioDoneDataCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                     handler: *mut Eio_File,
                                                     read_data: *const c_char,
                                                     size: c_uint)>;
pub type EioDoneStringCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                       handler: *mut Eio_File,
                                                       xattr_string: *const c_char)>;
pub type EioDoneDoubleCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                       handler: *mut Eio_File,
                                                       xattr_double: c_double)>;
pub type EioDoneIntCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                    handler: *mut Eio_File,
                                                    i: c_int)>;
pub type EioDoneEreadCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                      handler: *mut Eio_File,
                                                      decoded: *mut c_void)>;
pub type EioDoneReadCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                     handler: *mut Eio_File,
                                                     read_data: *mut c_void,
                                                     size: c_uint)>;
pub type EioDoneCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                 handler: *mut Eio_File)>;
pub type EioErrorCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                  handler: *mut Eio_File,
                                                  error: c_int)>;
pub type EioEetErrorCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                     handler: *mut Eio_File,
                                                     err: EetError)>;
#[repr(C)]
pub struct Eio_Progress {
    pub op: EioFileOp,
    pub current: c_longlong,
    pub max: c_longlong,
    pub percent: c_float,
    pub source: *const c_char,
    pub dest: *const c_char,
}
pub enum Eio_Monitor { }
#[repr(C)]
pub struct Eio_Monitor_Error {
    pub monitor: *mut Eio_Monitor,
    pub error: c_int,
}
#[repr(C)]
pub struct Eio_Monitor_Event {
    pub monitor: *mut Eio_Monitor,
    pub filename: *const c_char,
}

#[link(name = "eio")]
extern "C" {
    pub static mut eio_version: *mut Eio_Version;
    pub static mut EIO_MONITOR_FILE_CREATED: c_int;
    pub static mut EIO_MONITOR_FILE_DELETED: c_int;
    pub static mut EIO_MONITOR_FILE_MODIFIED: c_int;
    pub static mut EIO_MONITOR_FILE_CLOSED: c_int;
    pub static mut EIO_MONITOR_DIRECTORY_CREATED: c_int;
    pub static mut EIO_MONITOR_DIRECTORY_DELETED: c_int;
    pub static mut EIO_MONITOR_DIRECTORY_MODIFIED: c_int;
    pub static mut EIO_MONITOR_DIRECTORY_CLOSED: c_int;
    pub static mut EIO_MONITOR_SELF_RENAME: c_int;
    pub static mut EIO_MONITOR_SELF_DELETED: c_int;
    pub static mut EIO_MONITOR_ERROR: c_int;
}
#[link(name = "eio")]
extern "C" {
    pub fn eio_file_ls(dir: *const c_char,
                       filter_cb: EioFilterCb, main_cb: EioMainCb,
                       done_cb: EioDoneCb, error_cb: EioErrorCb,
                       data: *const c_void) -> *mut Eio_File;
    pub fn eio_file_direct_ls(dir: *const c_char,
                              filter_cb: EioFilterDirectCb,
                              main_cb: EioMainDirectCb,
                              done_cb: EioDoneCb, error_cb: EioErrorCb,
                              data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_stat_ls(dir: *const c_char,
                            filter_cb: EioFilterDirectCb,
                            main_cb: EioMainDirectCb, done_cb: EioDoneCb,
                            error_cb: EioErrorCb,
                            data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_dir_stat_ls(dir: *const c_char,
                           filter_cb: EioFilterDirectCb,
                           main_cb: EioMainDirectCb, done_cb: EioDoneCb,
                           error_cb: EioErrorCb,
                           data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_dir_direct_ls(dir: *const c_char,
                             filter_cb: EioFilterDirCb,
                             main_cb: EioMainDirectCb,
                             done_cb: EioDoneCb, error_cb: EioErrorCb,
                             data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_direct_stat(path: *const c_char,
                                done_cb: EioStatCb, error_cb: EioErrorCb,
                                data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_chmod(path: *const c_char, mode: mode_t,
                          done_cb: EioDoneCb, error_cb: EioErrorCb,
                          data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_chown(path: *const c_char,
                          user: *const c_char,
                          group: *const c_char,
                          done_cb: EioDoneCb, error_cb: EioErrorCb,
                          data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_unlink(path: *const c_char,
                           done_cb: EioDoneCb, error_cb: EioErrorCb,
                           data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_mkdir(path: *const c_char, mode: mode_t,
                          done_cb: EioDoneCb, error_cb: EioErrorCb,
                          data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_move(source: *const c_char,
                         dest: *const c_char,
                         progress_cb: EioProgressCb, done_cb: EioDoneCb,
                         error_cb: EioErrorCb,
                         data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_copy(source: *const c_char,
                         dest: *const c_char,
                         progress_cb: EioProgressCb, done_cb: EioDoneCb,
                         error_cb: EioErrorCb,
                         data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_dir_move(source: *const c_char,
                        dest: *const c_char,
                        filter_cb: EioFilterDirectCb,
                        progress_cb: EioProgressCb, done_cb: EioDoneCb,
                        error_cb: EioErrorCb,
                        data: *const c_void) -> *mut Eio_File;
    pub fn eio_dir_copy(source: *const c_char,
                        dest: *const c_char,
                        filter_cb: EioFilterDirectCb,
                        progress_cb: EioProgressCb, done_cb: EioDoneCb,
                        error_cb: EioErrorCb,
                        data: *const c_void) -> *mut Eio_File;
    pub fn eio_dir_unlink(path: *const c_char,
                          filter_cb: EioFilterDirectCb,
                          progress_cb: EioProgressCb, done_cb: EioDoneCb,
                          error_cb: EioErrorCb,
                          data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_xattr(path: *const c_char,
                          filter_cb: EioFilterCb, main_cb: EioMainCb,
                          done_cb: EioDoneCb, error_cb: EioErrorCb,
                          data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_xattr_int_set(path: *const c_char,
                                  attribute: *const c_char,
                                  xattr_int: c_int,
                                  flags: EinaXattrFlags,
                                  done_cb: EioDoneCb,
                                  error_cb: EioErrorCb,
                                  data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_xattr_double_set(path: *const c_char,
                                     attribute: *const c_char,
                                     xattr_double: c_double,
                                     flags: EinaXattrFlags,
                                     done_cb: EioDoneCb,
                                     error_cb: EioErrorCb,
                                     data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_xattr_string_set(path: *const c_char,
                                     attribute: *const c_char,
                                     xattr_string:
                                         *const c_char,
                                     flags: EinaXattrFlags,
                                     done_cb: EioDoneCb,
                                     error_cb: EioErrorCb,
                                     data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_xattr_set(path: *const c_char,
                              attribute: *const c_char,
                              xattr_data: *const c_char,
                              xattr_size: c_uint,
                              flags: EinaXattrFlags, done_cb: EioDoneCb,
                              error_cb: EioErrorCb,
                              data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_xattr_get(path: *const c_char,
                              attribute: *const c_char,
                              done_cb: EioDoneDataCb,
                              error_cb: EioErrorCb,
                              data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_xattr_int_get(path: *const c_char,
                                  attribute: *const c_char,
                                  done_cb: EioDoneIntCb,
                                  error_cb: EioErrorCb,
                                  data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_xattr_double_get(path: *const c_char,
                                     attribute: *const c_char,
                                     done_cb: EioDoneDoubleCb,
                                     error_cb: EioErrorCb,
                                     data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_xattr_string_get(path: *const c_char,
                                     attribute: *const c_char,
                                     done_cb: EioDoneStringCb,
                                     error_cb: EioErrorCb,
                                     data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_init() -> c_int;
    pub fn eio_shutdown() -> c_int;
    pub fn eio_memory_burst_limit_set(limit: size_t);
    pub fn eio_memory_burst_limit_get() -> size_t;
    pub fn eio_file_container_get(ls: *mut Eio_File)
     -> *mut c_void;
    pub fn eio_file_cancel(ls: *mut Eio_File) -> EinaBool;
    pub fn eio_file_check(ls: *mut Eio_File) -> EinaBool;
    pub fn eio_file_associate_add(ls: *mut Eio_File,
                                  key: *const c_char,
                                  data: *const c_void,
                                  free_cb: EinaFreeCb) -> EinaBool;
    pub fn eio_file_associate_direct_add(ls: *mut Eio_File,
                                         key: *const c_char,
                                         data: *const c_void,
                                         free_cb: EinaFreeCb) -> EinaBool;
    pub fn eio_file_associate_find(ls: *mut Eio_File,
                                   key: *const c_char)
     -> *mut c_void;
    pub fn eio_file_open(name: *const c_char,
                         shared: EinaBool, open_cb: EioOpenCb,
                         error_cb: EioErrorCb,
                         data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_close(f: *mut Eina_File, done_cb: EioDoneCb,
                          error_cb: EioErrorCb,
                          data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_map_all(f: *mut Eina_File, rule: EinaFilePopulate,
                            filter_cb: EioFilterMapCb, map_cb: EioMapCb,
                            error_cb: EioErrorCb,
                            data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_file_map_new(f: *mut Eina_File, rule: EinaFilePopulate,
                            offset: c_ulong,
                            length: c_ulong,
                            filter_cb: EioFilterMapCb, map_cb: EioMapCb,
                            error_cb: EioErrorCb,
                            data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_eet_open(filename: *const c_char,
                        mode: EetFileMode, eet_cb: EioEetOpenCb,
                        error_cb: EioErrorCb,
                        data: *const c_void) -> *mut Eio_File;
    pub fn eio_eet_close(ef: *mut Eet_File, done_cb: EioDoneCb,
                         error_cb: EioEetErrorCb,
                         data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_eet_sync(ef: *mut Eet_File, done_cb: EioDoneCb,
                        error_cb: EioEetErrorCb,
                        data: *const c_void) -> *mut Eio_File;
    pub fn eio_eet_data_write_cipher(ef: *mut Eet_File,
                                     edd: *mut Eet_Data_Descriptor,
                                     name: *const c_char,
                                     cipher_key:
                                         *const c_char,
                                     write_data: *mut c_void,
                                     compress: c_int,
                                     done_cb: EioDoneIntCb,
                                     error_cb: EioErrorCb,
                                     user_data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_eet_data_read_cipher(ef: *mut Eet_File,
                                    edd: *mut Eet_Data_Descriptor,
                                    name: *const c_char,
                                    cipher_key: *const c_char,
                                    done_cb: EioDoneEreadCb,
                                    error_cb: EioErrorCb,
                                    data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_eet_data_image_write_cipher(ef: *mut Eet_File,
                                           name:
                                               *const c_char,
                                           cipher_key:
                                               *const c_char,
                                           write_data:
                                               *mut c_void,
                                           w: c_uint,
                                           h: c_uint,
                                           alpha: c_int,
                                           compress: c_int,
                                           quality: c_int,
                                           lossy: c_int,
                                           done_cb: EioDoneIntCb,
                                           error_cb: EioErrorCb,
                                           user_data:
                                               *const c_void)
     -> *mut Eio_File;
    pub fn eio_eet_read_direct(ef: *mut Eet_File,
                               name: *const c_char,
                               done_cb: EioDoneDataCb,
                               error_cb: EioErrorCb,
                               data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_eet_read_cipher(ef: *mut Eet_File,
                               name: *const c_char,
                               cipher_key: *const c_char,
                               done_cb: EioDoneReadCb,
                               error_cb: EioErrorCb,
                               data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_eet_write_cipher(ef: *mut Eet_File,
                                name: *const c_char,
                                write_data: *mut c_void,
                                size: c_int,
                                compress: c_int,
                                cipher_key: *const c_char,
                                done_cb: EioDoneIntCb,
                                error_cb: EioErrorCb,
                                user_data: *const c_void)
     -> *mut Eio_File;
    pub fn eio_monitor_add(path: *const c_char)
     -> *mut Eio_Monitor;
    pub fn eio_monitor_stringshared_add(path: *const c_char)
     -> *mut Eio_Monitor;
    pub fn eio_monitor_del(monitor: *mut Eio_Monitor);
    pub fn eio_monitor_path_get(monitor: *mut Eio_Monitor)
     -> *const c_char;
}
