extern crate libc;
extern crate evas_sys;
extern crate eina_sys;

use libc::*;
use evas_sys::*;
use eina_sys::*;

/* automatically generated by rust-bindgen */

pub type EcoreXWindow = c_uint;
pub type EcoreXPixmap = c_uint;
pub type EcoreXAtom = c_uint;
#[repr(C)]
pub struct EcoreXIcon {
    pub width: c_uint,
    pub height: c_uint,
    pub data: *mut c_uint,
}
pub enum EcoreDirectFBWindow { }
pub enum EcoreWin32Window { }
pub enum EcoreWinCEWindow { }
pub enum EcoreCocoaWindow { }
pub enum EcoreEvas { }
pub type EcoreEvasEventCb = Option<unsafe extern "C" fn(ee: *mut EcoreEvas)>;
pub enum EcoreWlWindow { }
pub enum EcoreGetopt { }
pub enum EcoreGetoptDesc { }
pub enum EcoreUnionGetoptValue { }
pub type EcoreWindow = uintptr_t;
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EcoreEvasEngineType {
    ECORE_EVAS_ENGINE_SOFTWARE_BUFFER = 0,
    ECORE_EVAS_ENGINE_SOFTWARE_XLIB = 1,
    ECORE_EVAS_ENGINE_XRENDER_X11 = 2,
    ECORE_EVAS_ENGINE_OPENGL_X11 = 3,
    ECORE_EVAS_ENGINE_SOFTWARE_XCB = 4,
    ECORE_EVAS_ENGINE_XRENDER_XCB = 5,
    ECORE_EVAS_ENGINE_SOFTWARE_GDI = 6,
    ECORE_EVAS_ENGINE_SOFTWARE_DDRAW = 7,
    ECORE_EVAS_ENGINE_DIRECT3D = 8,
    ECORE_EVAS_ENGINE_OPENGL_GLEW = 9,
    ECORE_EVAS_ENGINE_OPENGL_COCOA = 10,
    ECORE_EVAS_ENGINE_SOFTWARE_SDL = 11,
    ECORE_EVAS_ENGINE_DIRECTFB = 12,
    ECORE_EVAS_ENGINE_SOFTWARE_FB = 13,
    ECORE_EVAS_ENGINE_SOFTWARE_8_X11 = 14,
    ECORE_EVAS_ENGINE_SOFTWARE_16_X11 = 15,
    ECORE_EVAS_ENGINE_SOFTWARE_16_DDRAW = 16,
    ECORE_EVAS_ENGINE_SOFTWARE_16_WINCE = 17,
    ECORE_EVAS_ENGINE_OPENGL_SDL = 18,
    ECORE_EVAS_ENGINE_EWS = 19,
    ECORE_EVAS_ENGINE_PSL1GHT = 20,
    ECORE_EVAS_ENGINE_WAYLAND_SHM = 21,
    ECORE_EVAS_ENGINE_WAYLAND_EGL = 22,
    ECORE_EVAS_ENGINE_DRM = 23,
    ECORE_EVAS_ENGINE_OPENGL_DRM = 24,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EcoreEvasAvoidDamagaeType {
    ECORE_EVAS_AVOID_DAMAGE_NONE = 0,
    ECORE_EVAS_AVOID_DAMAGE_EXPOSE = 1,
    ECORE_EVAS_AVOID_DAMAGE_BUILT_IN = 2,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EcoreEvasObjectAssociateFlags {
    ECORE_EVAS_OBJECT_ASSOCIATE_BASE = 0,
    ECORE_EVAS_OBJECT_ASSOCIATE_STACK = 1,
    ECORE_EVAS_OBJECT_ASSOCIATE_LAYER = 2,
    ECORE_EVAS_OBJECT_ASSOCIATE_DEL = 4,
}

#[link(name = "ecore_evas")]
extern "C" {
    pub static mut ECORE_EVAS_EWS_EVENT_MANAGER_CHANGE: c_int;
    pub static mut ECORE_EVAS_EWS_EVENT_ADD: c_int;
    pub static mut ECORE_EVAS_EWS_EVENT_DEL: c_int;
    pub static mut ECORE_EVAS_EWS_EVENT_RESIZE: c_int;
    pub static mut ECORE_EVAS_EWS_EVENT_MOVE: c_int;
    pub static mut ECORE_EVAS_EWS_EVENT_SHOW: c_int;
    pub static mut ECORE_EVAS_EWS_EVENT_HIDE: c_int;
    pub static mut ECORE_EVAS_EWS_EVENT_FOCUS: c_int;
    pub static mut ECORE_EVAS_EWS_EVENT_UNFOCUS: c_int;
    pub static mut ECORE_EVAS_EWS_EVENT_RAISE: c_int;
    pub static mut ECORE_EVAS_EWS_EVENT_LOWER: c_int;
    pub static mut ECORE_EVAS_EWS_EVENT_ACTIVATE: c_int;
    pub static mut ECORE_EVAS_EWS_EVENT_ICONIFIED_CHANGE:
               c_int;
    pub static mut ECORE_EVAS_EWS_EVENT_MAXIMIZED_CHANGE:
               c_int;
    pub static mut ECORE_EVAS_EWS_EVENT_LAYER_CHANGE: c_int;
    pub static mut ECORE_EVAS_EWS_EVENT_FULLSCREEN_CHANGE:
               c_int;
    pub static mut ECORE_EVAS_EWS_EVENT_CONFIG_CHANGE: c_int;
    pub static mut ECORE_EVAS_EXTN_CLIENT_ADD: c_int;
    pub static mut ECORE_EVAS_EXTN_CLIENT_DEL: c_int;
}
#[link(name = "ecore_evas")]
extern "C" {
    pub fn ecore_evas_engine_type_supported_get(engine: EcoreEvasEngineType)
     -> c_int;
    pub fn ecore_evas_init() -> c_int;
    pub fn ecore_evas_shutdown() -> c_int;
    pub fn ecore_evas_app_comp_sync_set(do_sync: EinaBool);
    pub fn ecore_evas_app_comp_sync_get() -> EinaBool;
    pub fn ecore_evas_engines_get() -> *mut EinaList;
    pub fn ecore_evas_engines_free(engines: *mut EinaList);
    pub fn ecore_evas_new(engine_name: *const c_char,
                          x: c_int, y: c_int,
                          w: c_int, h: c_int,
                          extra_options: *const c_char)
     -> *mut EcoreEvas;
    pub fn ecore_evas_alpha_set(ee: *mut EcoreEvas, alpha: EinaBool);
    pub fn ecore_evas_alpha_get(ee: *const EcoreEvas) -> EinaBool;
    pub fn ecore_evas_transparent_set(ee: *mut EcoreEvas,
                                      transparent: EinaBool);
    pub fn ecore_evas_transparent_get(ee: *const EcoreEvas) -> EinaBool;
    pub fn ecore_evas_geometry_get(ee: *const EcoreEvas,
                                   x: *mut c_int,
                                   y: *mut c_int,
                                   w: *mut c_int,
                                   h: *mut c_int);
    pub fn ecore_evas_request_geometry_get(ee: *const EcoreEvas,
                                           x: *mut c_int,
                                           y: *mut c_int,
                                           w: *mut c_int,
                                           h: *mut c_int);
    pub fn ecore_evas_focus_set(ee: *mut EcoreEvas, on: EinaBool);
    pub fn ecore_evas_focus_get(ee: *const EcoreEvas) -> EinaBool;
    pub fn ecore_evas_iconified_set(ee: *mut EcoreEvas, on: EinaBool);
    pub fn ecore_evas_iconified_get(ee: *const EcoreEvas) -> EinaBool;
    pub fn ecore_evas_borderless_set(ee: *mut EcoreEvas, on: EinaBool);
    pub fn ecore_evas_borderless_get(ee: *const EcoreEvas) -> EinaBool;
    pub fn ecore_evas_fullscreen_set(ee: *mut EcoreEvas, on: EinaBool);
    pub fn ecore_evas_fullscreen_get(ee: *const EcoreEvas) -> EinaBool;
    pub fn ecore_evas_window_group_set(ee: *mut EcoreEvas,
                                       ee_group: *const EcoreEvas);
    pub fn ecore_evas_window_group_get(ee: *const EcoreEvas)
     -> *const EcoreEvas;
    pub fn ecore_evas_aspect_set(ee: *mut EcoreEvas,
                                 aspect: c_double);
    pub fn ecore_evas_aspect_get(ee: *const EcoreEvas)
     -> c_double;
    pub fn ecore_evas_urgent_set(ee: *mut EcoreEvas, urgent: EinaBool);
    pub fn ecore_evas_urgent_get(ee: *const EcoreEvas) -> EinaBool;
    pub fn ecore_evas_modal_set(ee: *mut EcoreEvas, modal: EinaBool);
    pub fn ecore_evas_modal_get(ee: *const EcoreEvas) -> EinaBool;
    pub fn ecore_evas_demand_attention_set(ee: *mut EcoreEvas,
                                           demand: EinaBool);
    pub fn ecore_evas_demand_attention_get(ee: *const EcoreEvas)
     -> EinaBool;
    pub fn ecore_evas_focus_skip_set(ee: *mut EcoreEvas, skip: EinaBool);
    pub fn ecore_evas_focus_skip_get(ee: *const EcoreEvas) -> EinaBool;
    pub fn ecore_evas_ignore_events_set(ee: *mut EcoreEvas,
                                        ignore: EinaBool);
    pub fn ecore_evas_ignore_events_get(ee: *const EcoreEvas) -> EinaBool;
    pub fn ecore_evas_visibility_get(ee: *const EcoreEvas)
     -> c_int;
    pub fn ecore_evas_layer_set(ee: *mut EcoreEvas,
                                layer: c_int);
    pub fn ecore_evas_layer_get(ee: *const EcoreEvas)
     -> c_int;
    pub fn ecore_evas_maximized_set(ee: *mut EcoreEvas, on: EinaBool);
    pub fn ecore_evas_maximized_get(ee: *const EcoreEvas) -> EinaBool;
    pub fn ecore_evas_window_profile_supported_get(ee: *const EcoreEvas)
     -> EinaBool;
    pub fn ecore_evas_window_profile_set(ee: *mut EcoreEvas,
                                         profile:
                                             *const c_char);
    pub fn ecore_evas_window_profile_get(ee: *const EcoreEvas)
     -> *const c_char;
    pub fn ecore_evas_window_available_profiles_set(ee: *mut EcoreEvas,
                                                    profiles:
                                                        *mut *const c_char,
                                                    count:
                                                        c_uint);
    pub fn ecore_evas_window_available_profiles_get(ee: *mut EcoreEvas,
                                                    profiles:
                                                        *mut *mut *mut c_char,
                                                    count:
                                                        *mut c_uint)
     -> EinaBool;
    pub fn ecore_evas_wm_rotation_supported_get(ee: *const EcoreEvas)
     -> EinaBool;
    pub fn ecore_evas_wm_rotation_preferred_rotation_set(ee: *mut EcoreEvas,
                                                         rotation:
                                                             c_int);
    pub fn ecore_evas_wm_rotation_preferred_rotation_get(ee:
                                                             *const EcoreEvas)
     -> c_int;
    pub fn ecore_evas_wm_rotation_available_rotations_set(ee: *mut EcoreEvas,
                                                          rotations:
                                                              *const c_int,
                                                          count:
                                                              c_uint);
    pub fn ecore_evas_wm_rotation_available_rotations_get(ee:
                                                              *const EcoreEvas,
                                                          rotations:
                                                              *mut *mut c_int,
                                                          count:
                                                              *mut c_uint)
     -> EinaBool;
    pub fn ecore_evas_wm_rotation_manual_rotation_done_set(ee:
                                                               *mut EcoreEvas,
                                                           set: EinaBool);
    pub fn ecore_evas_wm_rotation_manual_rotation_done_get(ee:
                                                               *const EcoreEvas)
     -> EinaBool;
    pub fn ecore_evas_wm_rotation_manual_rotation_done(ee: *mut EcoreEvas);
    pub fn ecore_evas_aux_hints_supported_get(ee: *const EcoreEvas)
     -> *const EinaList;
    pub fn ecore_evas_aux_hints_allowed_get(ee: *const EcoreEvas)
     -> *mut EinaList;
    pub fn ecore_evas_aux_hint_add(ee: *mut EcoreEvas,
                                   hint: *const c_char,
                                   val: *const c_char)
     -> c_int;
    pub fn ecore_evas_aux_hint_del(ee: *mut EcoreEvas,
                                   id: c_int) -> EinaBool;
    pub fn ecore_evas_aux_hint_val_set(ee: *mut EcoreEvas,
                                       id: c_int,
                                       val: *const c_char)
     -> EinaBool;
    pub fn ecore_evas_aux_hint_val_get(ee: *const EcoreEvas,
                                       id: c_int)
     -> *const c_char;
    pub fn ecore_evas_aux_hint_id_get(ee: *const EcoreEvas,
                                      hint: *const c_char)
     -> c_int;
    pub fn ecore_evas_msg_parent_send(ee: *mut EcoreEvas,
                                      msg_domain: c_int,
                                      msg_id: c_int,
                                      data: *mut c_void,
                                      size: c_int);
    pub fn ecore_evas_msg_send(ee: *mut EcoreEvas,
                               msg_domain: c_int,
                               msg_id: c_int,
                               data: *mut c_void,
                               size: c_int);
    pub fn ecore_evas_callback_msg_parent_handle_set(ee: *mut EcoreEvas,
                                                     func_parent_handle:
                                                         Option<unsafe extern "C" fn(ee:
                                                                                                        *mut EcoreEvas,
                                                                                                    msg_domain:
                                                                                                        c_int,
                                                                                                    msg_id:
                                                                                                        c_int,
                                                                                                    data:
                                                                                                        *mut c_void,
                                                                                                    size:
                                                                                                        c_int)>);
    pub fn ecore_evas_callback_msg_handle_set(ee: *mut EcoreEvas,
                                              func_handle:
                                                  Option<unsafe extern "C" fn(ee:
                                                                                                 *mut EcoreEvas,
                                                                                             msg_domain:
                                                                                                 c_int,
                                                                                             msg_id:
                                                                                                 c_int,
                                                                                             data:
                                                                                                 *mut c_void,
                                                                                             size:
                                                                                                 c_int)>);
    pub fn ecore_evas_move(ee: *mut EcoreEvas, x: c_int,
                           y: c_int);
    pub fn ecore_evas_resize(ee: *mut EcoreEvas, w: c_int,
                             h: c_int);
    pub fn ecore_evas_move_resize(ee: *mut EcoreEvas,
                                  x: c_int,
                                  y: c_int,
                                  w: c_int,
                                  h: c_int);
    pub fn ecore_evas_rotation_set(ee: *mut EcoreEvas,
                                   rot: c_int);
    pub fn ecore_evas_rotation_with_resize_set(ee: *mut EcoreEvas,
                                               rot: c_int);
    pub fn ecore_evas_rotation_get(ee: *const EcoreEvas)
     -> c_int;
    pub fn ecore_evas_raise(ee: *mut EcoreEvas);
    pub fn ecore_evas_lower(ee: *mut EcoreEvas);
    pub fn ecore_evas_title_set(ee: *mut EcoreEvas,
                                t: *const c_char);
    pub fn ecore_evas_title_get(ee: *const EcoreEvas)
     -> *const c_char;
    pub fn ecore_evas_name_class_set(ee: *mut EcoreEvas,
                                     n: *const c_char,
                                     c: *const c_char);
    pub fn ecore_evas_name_class_get(ee: *const EcoreEvas,
                                     n: *mut *const c_char,
                                     c: *mut *const c_char);
    pub fn ecore_evas_window_get(ee: *const EcoreEvas) -> EcoreWindow;
    pub fn ecore_evas_software_x11_new(disp_name:
                                           *const c_char,
                                       parent: EcoreXWindow,
                                       x: c_int,
                                       y: c_int,
                                       w: c_int,
                                       h: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_software_x11_window_get(ee: *const EcoreEvas)
     -> EcoreXWindow;
    pub fn ecore_evas_software_x11_direct_resize_set(ee: *mut EcoreEvas,
                                                     on: EinaBool);
    pub fn ecore_evas_software_x11_direct_resize_get(ee: *const EcoreEvas)
     -> EinaBool;
    pub fn ecore_evas_software_x11_extra_event_window_add(ee: *mut EcoreEvas,
                                                          win:
                                                              EcoreXWindow);
    pub fn ecore_evas_software_x11_pixmap_new(disp_name:
                                                  *const c_char,
                                              parent: EcoreXWindow,
                                              x: c_int,
                                              y: c_int,
                                              w: c_int,
                                              h: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_software_x11_pixmap_get(ee: *const EcoreEvas)
     -> EcoreXPixmap;
    pub fn ecore_evas_gl_x11_new(disp_name: *const c_char,
                                 parent: EcoreXWindow,
                                 x: c_int,
                                 y: c_int,
                                 w: c_int,
                                 h: c_int) -> *mut EcoreEvas;
    pub fn ecore_evas_gl_x11_options_new(disp_name:
                                             *const c_char,
                                         parent: EcoreXWindow,
                                         x: c_int,
                                         y: c_int,
                                         w: c_int,
                                         h: c_int,
                                         opt: *const c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_gl_x11_window_get(ee: *const EcoreEvas)
     -> EcoreXWindow;
    pub fn ecore_evas_gl_x11_direct_resize_set(ee: *mut EcoreEvas,
                                               on: EinaBool);
    pub fn ecore_evas_gl_x11_direct_resize_get(ee: *const EcoreEvas)
     -> EinaBool;
    pub fn ecore_evas_gl_x11_extra_event_window_add(ee: *mut EcoreEvas,
                                                    win: EcoreXWindow);
    pub fn ecore_evas_gl_x11_pre_post_swap_callback_set(ee: *const EcoreEvas,
                                                        data:
                                                            *mut c_void,
                                                        pre_cb:
                                                            Option<unsafe extern "C" fn(data:
                                                                                                           *mut c_void,
                                                                                                       e:
                                                                                                           *mut Evas)>,
                                                        post_cb:
                                                            Option<unsafe extern "C" fn(data:
                                                                                                           *mut c_void,
                                                                                                       e:
                                                                                                           *mut Evas)>);
    pub fn ecore_evas_gl_x11_pixmap_new(disp_name:
                                            *const c_char,
                                        parent: EcoreXWindow,
                                        x: c_int,
                                        y: c_int,
                                        w: c_int,
                                        h: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_gl_x11_pixmap_get(ee: *const EcoreEvas)
     -> EcoreXPixmap;
    pub fn ecore_evas_xrender_x11_new(disp_name:
                                          *const c_char,
                                      parent: EcoreXWindow,
                                      x: c_int,
                                      y: c_int,
                                      w: c_int,
                                      h: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_xrender_x11_window_get(ee: *const EcoreEvas)
     -> EcoreXWindow;
    pub fn ecore_evas_xrender_x11_direct_resize_set(ee: *mut EcoreEvas,
                                                    on: EinaBool);
    pub fn ecore_evas_xrender_x11_direct_resize_get(ee: *const EcoreEvas)
     -> EinaBool;
    pub fn ecore_evas_xrender_x11_extra_event_window_add(ee: *mut EcoreEvas,
                                                         win: EcoreXWindow);
    pub fn ecore_evas_software_x11_8_new(disp_name:
                                             *const c_char,
                                         parent: EcoreXWindow,
                                         x: c_int,
                                         y: c_int,
                                         w: c_int,
                                         h: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_software_x11_8_window_get(ee: *const EcoreEvas)
     -> EcoreXWindow;
    pub fn ecore_evas_software_x11_8_subwindow_get(ee: *const EcoreEvas)
     -> EcoreXWindow;
    pub fn ecore_evas_software_x11_8_direct_resize_set(ee: *mut EcoreEvas,
                                                       on: EinaBool);
    pub fn ecore_evas_software_x11_8_direct_resize_get(ee: *const EcoreEvas)
     -> EinaBool;
    pub fn ecore_evas_software_x11_8_extra_event_window_add(ee:
                                                                *mut EcoreEvas,
                                                            win:
                                                                EcoreXWindow);
    pub fn ecore_evas_software_x11_16_new(disp_name:
                                              *const c_char,
                                          parent: EcoreXWindow,
                                          x: c_int,
                                          y: c_int,
                                          w: c_int,
                                          h: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_software_x11_16_window_get(ee: *const EcoreEvas)
     -> EcoreXWindow;
    pub fn ecore_evas_software_x11_16_direct_resize_set(ee: *mut EcoreEvas,
                                                        on: EinaBool);
    pub fn ecore_evas_software_x11_16_direct_resize_get(ee: *const EcoreEvas)
     -> EinaBool;
    pub fn ecore_evas_software_x11_16_extra_event_window_add(ee:
                                                                 *mut EcoreEvas,
                                                             win:
                                                                 EcoreXWindow);
    pub fn ecore_evas_fb_new(disp_name: *const c_char,
                             rotation: c_int,
                             w: c_int,
                             h: c_int) -> *mut EcoreEvas;
    pub fn ecore_evas_directfb_new(disp_name: *const c_char,
                                   windowed: c_int,
                                   x: c_int,
                                   y: c_int,
                                   w: c_int,
                                   h: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_directfb_window_get(ee: *const EcoreEvas)
     -> *mut EcoreDirectFBWindow;
    pub fn ecore_evas_wayland_shm_new(disp_name:
                                          *const c_char,
                                      parent: c_uint,
                                      x: c_int,
                                      y: c_int,
                                      w: c_int,
                                      h: c_int,
                                      frame: EinaBool) -> *mut EcoreEvas;
    pub fn ecore_evas_wayland_egl_new(disp_name:
                                          *const c_char,
                                      parent: c_uint,
                                      x: c_int,
                                      y: c_int,
                                      w: c_int,
                                      h: c_int,
                                      frame: EinaBool) -> *mut EcoreEvas;
    pub fn ecore_evas_wayland_resize(ee: *mut EcoreEvas,
                                     location: c_int);
    pub fn ecore_evas_wayland_move(ee: *mut EcoreEvas,
                                   x: c_int,
                                   y: c_int);
    pub fn ecore_evas_wayland_pointer_set(ee: *mut EcoreEvas,
                                          hot_x: c_int,
                                          hot_y: c_int);
    pub fn ecore_evas_wayland_type_set(ee: *mut EcoreEvas,
                                       _type: c_int);
    pub fn ecore_evas_wayland_window_get(ee: *const EcoreEvas)
     -> *mut EcoreWlWindow;
    pub fn ecore_evas_drm_new(device: *const c_char,
                              parent: c_uint,
                              x: c_int,
                              y: c_int,
                              w: c_int,
                              h: c_int) -> *mut EcoreEvas;
    pub fn ecore_evas_gl_drm_new(device: *const c_char,
                                 parent: c_uint,
                                 x: c_int,
                                 y: c_int,
                                 w: c_int,
                                 h: c_int) -> *mut EcoreEvas;
    pub fn ecore_evas_buffer_new(w: c_int,
                                 h: c_int) -> *mut EcoreEvas;
    pub fn ecore_evas_buffer_allocfunc_new(w: c_int,
                                           h: c_int,
                                           alloc_func:
                                               Option<unsafe extern "C" fn(data:
                                                                                              *mut c_void,
                                                                                          size:
                                                                                              c_int)
                                                                         ->
                                                                             *mut c_void>,
                                           free_func:
                                               Option<unsafe extern "C" fn(data:
                                                                                              *mut c_void,
                                                                                          pix:
                                                                                              *mut c_void)>,
                                           data:
                                               *const c_void)
     -> *mut EcoreEvas;
    pub fn ecore_evas_buffer_pixels_get(ee: *mut EcoreEvas)
     -> *const c_void;
    pub fn ecore_evas_buffer_ecore_evas_parent_get(ee: *mut EcoreEvas)
     -> *mut EcoreEvas;
    pub fn ecore_evas_ews_new(x: c_int,
                              y: c_int,
                              w: c_int,
                              h: c_int) -> *mut EcoreEvas;
    pub fn ecore_evas_ews_backing_store_get(ee: *const EcoreEvas)
     -> *mut EvasObject;
    pub fn ecore_evas_ews_delete_request(ee: *mut EcoreEvas);
    pub fn ecore_evas_object_image_new(ee_target: *mut EcoreEvas)
     -> *mut EvasObject;
    pub fn ecore_evas_object_ecore_evas_get(obj: *mut EvasObject)
     -> *mut EcoreEvas;
    pub fn ecore_evas_object_evas_get(obj: *mut EvasObject) -> *mut Evas;
    pub fn ecore_evas_software_gdi_new(parent: *mut EcoreWin32Window,
                                       x: c_int,
                                       y: c_int,
                                       width: c_int,
                                       height: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_software_ddraw_new(parent: *mut EcoreWin32Window,
                                         x: c_int,
                                         y: c_int,
                                         width: c_int,
                                         height: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_software_16_ddraw_new(parent: *mut EcoreWin32Window,
                                            x: c_int,
                                            y: c_int,
                                            width: c_int,
                                            height: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_direct3d_new(parent: *mut EcoreWin32Window,
                                   x: c_int,
                                   y: c_int,
                                   width: c_int,
                                   height: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_gl_glew_new(parent: *mut EcoreWin32Window,
                                  x: c_int,
                                  y: c_int,
                                  width: c_int,
                                  height: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_win32_window_get(ee: *const EcoreEvas)
     -> *mut EcoreWin32Window;
    pub fn ecore_evas_sdl_new(name: *const c_char,
                              w: c_int,
                              h: c_int,
                              fullscreen: c_int,
                              hwsurface: c_int,
                              noframe: c_int,
                              alpha: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_sdl16_new(name: *const c_char,
                                w: c_int,
                                h: c_int,
                                fullscreen: c_int,
                                hwsurface: c_int,
                                noframe: c_int,
                                alpha: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_gl_sdl_new(name: *const c_char,
                                 w: c_int,
                                 h: c_int,
                                 fullscreen: c_int,
                                 noframe: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_software_wince_new(parent: *mut EcoreWinCEWindow,
                                         x: c_int,
                                         y: c_int,
                                         width: c_int,
                                         height: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_software_wince_fb_new(parent: *mut EcoreWinCEWindow,
                                            x: c_int,
                                            y: c_int,
                                            width: c_int,
                                            height: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_software_wince_gapi_new(parent: *mut EcoreWinCEWindow,
                                              x: c_int,
                                              y: c_int,
                                              width: c_int,
                                              height: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_software_wince_ddraw_new(parent:
                                                   *mut EcoreWinCEWindow,
                                               x: c_int,
                                               y: c_int,
                                               width: c_int,
                                               height: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_software_wince_gdi_new(parent: *mut EcoreWinCEWindow,
                                             x: c_int,
                                             y: c_int,
                                             width: c_int,
                                             height: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_software_wince_window_get(ee: *const EcoreEvas)
     -> *mut EcoreWinCEWindow;
    pub fn ecore_evas_cocoa_new(parent: *mut EcoreCocoaWindow,
                                x: c_int,
                                y: c_int,
                                w: c_int,
                                h: c_int) -> *mut EcoreEvas;
    pub fn ecore_evas_psl1ght_new(name: *const c_char,
                                  w: c_int,
                                  h: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_engine_name_get(ee: *const EcoreEvas)
     -> *const c_char;
    pub fn ecore_evas_ecore_evas_get(e: *const Evas) -> *mut EcoreEvas;
    pub fn ecore_evas_free(ee: *mut EcoreEvas);
    pub fn ecore_evas_data_get(ee: *const EcoreEvas,
                               key: *const c_char)
     -> *mut c_void;
    pub fn ecore_evas_data_set(ee: *mut EcoreEvas,
                               key: *const c_char,
                               data: *const c_void);
    pub fn ecore_evas_callback_resize_set(ee: *mut EcoreEvas,
                                          func: EcoreEvasEventCb);
    pub fn ecore_evas_callback_move_set(ee: *mut EcoreEvas,
                                        func: EcoreEvasEventCb);
    pub fn ecore_evas_callback_show_set(ee: *mut EcoreEvas,
                                        func: EcoreEvasEventCb);
    pub fn ecore_evas_callback_hide_set(ee: *mut EcoreEvas,
                                        func: EcoreEvasEventCb);
    pub fn ecore_evas_callback_delete_request_set(ee: *mut EcoreEvas,
                                                  func: EcoreEvasEventCb);
    pub fn ecore_evas_callback_destroy_set(ee: *mut EcoreEvas,
                                           func: EcoreEvasEventCb);
    pub fn ecore_evas_callback_focus_in_set(ee: *mut EcoreEvas,
                                            func: EcoreEvasEventCb);
    pub fn ecore_evas_callback_focus_out_set(ee: *mut EcoreEvas,
                                             func: EcoreEvasEventCb);
    pub fn ecore_evas_callback_sticky_set(ee: *mut EcoreEvas,
                                          func: EcoreEvasEventCb);
    pub fn ecore_evas_callback_unsticky_set(ee: *mut EcoreEvas,
                                            func: EcoreEvasEventCb);
    pub fn ecore_evas_callback_mouse_in_set(ee: *mut EcoreEvas,
                                            func: EcoreEvasEventCb);
    pub fn ecore_evas_callback_mouse_out_set(ee: *mut EcoreEvas,
                                             func: EcoreEvasEventCb);
    pub fn ecore_evas_callback_pre_render_set(ee: *mut EcoreEvas,
                                              func: EcoreEvasEventCb);
    pub fn ecore_evas_callback_post_render_set(ee: *mut EcoreEvas,
                                               func: EcoreEvasEventCb);
    pub fn ecore_evas_callback_pre_free_set(ee: *mut EcoreEvas,
                                            func: EcoreEvasEventCb);
    pub fn ecore_evas_callback_state_change_set(ee: *mut EcoreEvas,
                                                func: EcoreEvasEventCb);
    pub fn ecore_evas_get(ee: *const EcoreEvas) -> *mut Evas;
    pub fn ecore_evas_managed_move(ee: *mut EcoreEvas,
                                   x: c_int,
                                   y: c_int);
    pub fn ecore_evas_shaped_set(ee: *mut EcoreEvas, shaped: EinaBool);
    pub fn ecore_evas_shaped_get(ee: *const EcoreEvas) -> EinaBool;
    pub fn ecore_evas_show(ee: *mut EcoreEvas);
    pub fn ecore_evas_hide(ee: *mut EcoreEvas);
    pub fn ecore_evas_activate(ee: *mut EcoreEvas);
    pub fn ecore_evas_size_min_set(ee: *mut EcoreEvas,
                                   w: c_int,
                                   h: c_int);
    pub fn ecore_evas_size_min_get(ee: *const EcoreEvas,
                                   w: *mut c_int,
                                   h: *mut c_int);
    pub fn ecore_evas_size_max_set(ee: *mut EcoreEvas,
                                   w: c_int,
                                   h: c_int);
    pub fn ecore_evas_size_max_get(ee: *const EcoreEvas,
                                   w: *mut c_int,
                                   h: *mut c_int);
    pub fn ecore_evas_size_base_set(ee: *mut EcoreEvas,
                                    w: c_int,
                                    h: c_int);
    pub fn ecore_evas_size_base_get(ee: *const EcoreEvas,
                                    w: *mut c_int,
                                    h: *mut c_int);
    pub fn ecore_evas_size_step_set(ee: *mut EcoreEvas,
                                    w: c_int,
                                    h: c_int);
    pub fn ecore_evas_size_step_get(ee: *const EcoreEvas,
                                    w: *mut c_int,
                                    h: *mut c_int);
    pub fn ecore_evas_cursor_set(ee: *mut EcoreEvas,
                                 file: *const c_char,
                                 layer: c_int,
                                 hot_x: c_int,
                                 hot_y: c_int);
    pub fn ecore_evas_cursor_get(ee: *const EcoreEvas,
                                 obj: *mut *mut EvasObject,
                                 layer: *mut c_int,
                                 hot_x: *mut c_int,
                                 hot_y: *mut c_int);
    pub fn ecore_evas_object_cursor_set(ee: *mut EcoreEvas,
                                        obj: *mut EvasObject,
                                        layer: c_int,
                                        hot_x: c_int,
                                        hot_y: c_int);
    pub fn ecore_evas_cursor_unset(ee: *mut EcoreEvas) -> *mut EvasObject;
    pub fn ecore_evas_override_set(ee: *mut EcoreEvas, on: EinaBool);
    pub fn ecore_evas_override_get(ee: *const EcoreEvas) -> EinaBool;
    pub fn ecore_evas_avoid_damage_set(ee: *mut EcoreEvas,
                                       on: EcoreEvasAvoidDamagaeType);
    pub fn ecore_evas_avoid_damage_get(ee: *const EcoreEvas)
     -> EcoreEvasAvoidDamagaeType;
    pub fn ecore_evas_withdrawn_set(ee: *mut EcoreEvas,
                                    withdrawn: EinaBool);
    pub fn ecore_evas_withdrawn_get(ee: *const EcoreEvas) -> EinaBool;
    pub fn ecore_evas_sticky_set(ee: *mut EcoreEvas, sticky: EinaBool);
    pub fn ecore_evas_sticky_get(ee: *const EcoreEvas) -> EinaBool;
    pub fn ecore_evas_manual_render_set(ee: *mut EcoreEvas,
                                        manual_render: EinaBool);
    pub fn ecore_evas_manual_render_get(ee: *const EcoreEvas) -> EinaBool;
    pub fn ecore_evas_input_event_register(ee: *mut EcoreEvas);
    pub fn ecore_evas_input_event_unregister(ee: *mut EcoreEvas);
    pub fn ecore_evas_manual_render(ee: *mut EcoreEvas);
    pub fn ecore_evas_comp_sync_set(ee: *mut EcoreEvas, do_sync: EinaBool);
    pub fn ecore_evas_comp_sync_get(ee: *const EcoreEvas) -> EinaBool;
    pub fn ecore_evas_screen_geometry_get(ee: *const EcoreEvas,
                                          x: *mut c_int,
                                          y: *mut c_int,
                                          w: *mut c_int,
                                          h: *mut c_int);
    pub fn ecore_evas_screen_dpi_get(ee: *const EcoreEvas,
                                     xdpi: *mut c_int,
                                     ydpi: *mut c_int);
    pub fn ecore_evas_draw_frame_set(ee: *mut EcoreEvas,
                                     draw_frame: EinaBool);
    pub fn ecore_evas_draw_frame_get(ee: *const EcoreEvas) -> EinaBool;
    pub fn ecore_evas_object_associate(ee: *mut EcoreEvas,
                                       obj: *mut EvasObject,
                                       flags:
                                           EcoreEvasObjectAssociateFlags)
     -> EinaBool;
    pub fn ecore_evas_object_dissociate(ee: *mut EcoreEvas,
                                        obj: *mut EvasObject) -> EinaBool;
    pub fn ecore_evas_object_associate_get(ee: *const EcoreEvas)
     -> *mut EvasObject;
    pub fn ecore_getopt_callback_ecore_evas_list_engines(parser:
                                                             *const EcoreGetopt,
                                                         desc:
                                                             *const EcoreGetoptDesc,
                                                         str:
                                                             *const c_char,
                                                         data:
                                                             *mut c_void,
                                                         storage:
                                                             *mut EcoreGetoptValue)
     -> c_uchar;
    pub fn ecore_evas_ecore_evas_list_get() -> *mut EinaList;
    pub fn ecore_evas_sub_ecore_evas_list_get(ee: *const EcoreEvas)
     -> *mut EinaList;
    pub fn ecore_evas_x11_leader_set(ee: *mut EcoreEvas,
                                     win: EcoreXWindow);
    pub fn ecore_evas_x11_leader_get(ee: *mut EcoreEvas) -> EcoreXWindow;
    pub fn ecore_evas_x11_leader_default_set(ee: *mut EcoreEvas);
    pub fn ecore_evas_x11_shape_input_rectangle_set(ee: *mut EcoreEvas,
                                                    x: c_int,
                                                    y: c_int,
                                                    w: c_int,
                                                    h: c_int);
    pub fn ecore_evas_x11_shape_input_rectangle_add(ee: *mut EcoreEvas,
                                                    x: c_int,
                                                    y: c_int,
                                                    w: c_int,
                                                    h: c_int);
    pub fn ecore_evas_x11_shape_input_rectangle_subtract(ee: *mut EcoreEvas,
                                                         x:
                                                             c_int,
                                                         y:
                                                             c_int,
                                                         w:
                                                             c_int,
                                                         h:
                                                             c_int);
    pub fn ecore_evas_x11_shape_input_empty(ee: *mut EcoreEvas);
    pub fn ecore_evas_x11_shape_input_reset(ee: *mut EcoreEvas);
    pub fn ecore_evas_x11_shape_input_apply(ee: *mut EcoreEvas);
    pub fn ecore_evas_ews_engine_set(engine: *const c_char,
                                     options: *const c_char)
     -> EinaBool;
    pub fn ecore_evas_ews_setup(x: c_int,
                                y: c_int,
                                w: c_int,
                                h: c_int) -> EinaBool;
    pub fn ecore_evas_ews_ecore_evas_get() -> *mut EcoreEvas;
    pub fn ecore_evas_ews_evas_get() -> *mut Evas;
    pub fn ecore_evas_ews_background_get() -> *mut EvasObject;
    pub fn ecore_evas_ews_background_set(o: *mut EvasObject);
    pub fn ecore_evas_ews_children_get() -> *const EinaList;
    pub fn ecore_evas_ews_manager_set(manager: *const c_void);
    pub fn ecore_evas_ews_manager_get() -> *const c_void;
    pub fn ecore_evas_extn_socket_new(w: c_int,
                                      h: c_int)
     -> *mut EcoreEvas;
    pub fn ecore_evas_extn_socket_listen(ee: *mut EcoreEvas,
                                         svcname:
                                             *const c_char,
                                         svcnum: c_int,
                                         svcsys: EinaBool) -> EinaBool;
    pub fn ecore_evas_extn_socket_events_block_set(ee: *mut EcoreEvas,
                                                   events_block: EinaBool);
    pub fn ecore_evas_extn_socket_events_block_get(ee: *mut EcoreEvas)
     -> EinaBool;
    pub fn ecore_evas_extn_plug_object_data_lock(obj: *mut EvasObject);
    pub fn ecore_evas_extn_plug_object_data_unlock(obj: *mut EvasObject);
    pub fn ecore_evas_extn_plug_new(ee_target: *mut EcoreEvas)
     -> *mut EvasObject;
    pub fn ecore_evas_extn_plug_connect(obj: *mut EvasObject,
                                        svcname:
                                            *const c_char,
                                        svcnum: c_int,
                                        svcsys: EinaBool) -> EinaBool;
    pub fn ecore_evas_pointer_xy_get(ee: *const EcoreEvas,
                                     x: *mut EvasCoord, y: *mut EvasCoord);
    pub fn ecore_evas_pointer_warp(ee: *const EcoreEvas, x: EvasCoord,
                                   y: EvasCoord) -> EinaBool;
    pub fn ecore_evas_pixmap_visual_get(ee: *const EcoreEvas)
     -> *mut c_void;
    pub fn ecore_evas_pixmap_colormap_get(ee: *const EcoreEvas)
     -> c_ulong;
    pub fn ecore_evas_pixmap_depth_get(ee: *const EcoreEvas)
     -> c_int;
}
