extern crate libc;
extern crate eina_sys;
extern crate eo_sys;
extern crate evas_sys;

use libc::*;
use eina_sys::*;
use eo_sys::*;
use evas_sys::*;
/* automatically generated by rust-bindgen */

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeCursor {
    EDJE_CURSOR_MAIN = 0,
    EDJE_CURSOR_SELECTION_BEGIN = 1,
    EDJE_CURSOR_SELECTION_END = 2,
    EDJE_CURSOR_PREEDIT_START = 3,
    EDJE_CURSOR_PREEDIT_END = 4,
    EDJE_CURSOR_USER = 5,
    EDJE_CURSOR_USER_EXTRA = 6,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeDragDir {
    EDJE_DRAG_DIR_NONE = 0,
    EDJE_DRAG_DIR_X = 1,
    EDJE_DRAG_DIR_Y = 2,
    EDJE_DRAG_DIR_XY = 3,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeLoadError {
    EDJE_LOAD_ERROR_NONE = 0,
    EDJE_LOAD_ERROR_GENERIC = 1,
    EDJE_LOAD_ERROR_DOES_NOT_EXIST = 2,
    EDJE_LOAD_ERROR_PERMISSION_DENIED = 3,
    EDJE_LOAD_ERROR_RESOURCE_ALLOCATION_FAILED = 4,
    EDJE_LOAD_ERROR_CORRUPT_FILE = 5,
    EDJE_LOAD_ERROR_UNKNOWN_FORMAT = 6,
    EDJE_LOAD_ERROR_INCOMPATIBLE_FILE = 7,
    EDJE_LOAD_ERROR_UNKNOWN_COLLECTION = 8,
    EDJE_LOAD_ERROR_RECURSIVE_REFERENCE = 9,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeTextAutocapitalType {
    EDJE_TEXT_AUTOCAPITAL_TYPE_NONE = 0,
    EDJE_TEXT_AUTOCAPITAL_TYPE_WORD = 1,
    EDJE_TEXT_AUTOCAPITAL_TYPE_SENTENCE = 2,
    EDJE_TEXT_AUTOCAPITAL_TYPE_ALLCHARACTER = 3,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeInputHints {
    EDJE_INPUT_HINT_NONE = 0,
    EDJE_INPUT_HINT_AUTO_COMPLETE = 1,
    EDJE_INPUT_HINT_SENSITIVE_DATA = 2,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeInputPanelLang {
    EDJE_INPUT_PANEL_LANG_AUTOMATIC = 0,
    EDJE_INPUT_PANEL_LANG_ALPHABET = 1,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeInputPanelReturnKeyType {
    EDJE_INPUT_PANEL_RETURN_KEY_TYPE_DEFAULT = 0,
    EDJE_INPUT_PANEL_RETURN_KEY_TYPE_DONE = 1,
    EDJE_INPUT_PANEL_RETURN_KEY_TYPE_GO = 2,
    EDJE_INPUT_PANEL_RETURN_KEY_TYPE_JOIN = 3,
    EDJE_INPUT_PANEL_RETURN_KEY_TYPE_LOGIN = 4,
    EDJE_INPUT_PANEL_RETURN_KEY_TYPE_NEXT = 5,
    EDJE_INPUT_PANEL_RETURN_KEY_TYPE_SEARCH = 6,
    EDJE_INPUT_PANEL_RETURN_KEY_TYPE_SEND = 7,
    EDJE_INPUT_PANEL_RETURN_KEY_TYPE_SIGNIN = 8,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeInputPanelLayout {
    EDJE_INPUT_PANEL_LAYOUT_NORMAL = 0,
    EDJE_INPUT_PANEL_LAYOUT_NUMBER = 1,
    EDJE_INPUT_PANEL_LAYOUT_EMAIL = 2,
    EDJE_INPUT_PANEL_LAYOUT_URL = 3,
    EDJE_INPUT_PANEL_LAYOUT_PHONENUMBER = 4,
    EDJE_INPUT_PANEL_LAYOUT_IP = 5,
    EDJE_INPUT_PANEL_LAYOUT_MONTH = 6,
    EDJE_INPUT_PANEL_LAYOUT_NUMBERONLY = 7,
    EDJE_INPUT_PANEL_LAYOUT_INVALID = 8,
    EDJE_INPUT_PANEL_LAYOUT_HEX = 9,
    EDJE_INPUT_PANEL_LAYOUT_TERMINAL = 10,
    EDJE_INPUT_PANEL_LAYOUT_PASSWORD = 11,
    EDJE_INPUT_PANEL_LAYOUT_DATETIME = 12,
    EDJE_INPUT_PANEL_LAYOUT_EMOTICON = 13,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeExternalParamType {
    EDJE_EXTERNAL_PARAM_TYPE_INT = 0,
    EDJE_EXTERNAL_PARAM_TYPE_DOUBLE = 1,
    EDJE_EXTERNAL_PARAM_TYPE_STRING = 2,
    EDJE_EXTERNAL_PARAM_TYPE_BOOL = 3,
    EDJE_EXTERNAL_PARAM_TYPE_CHOICE = 4,
    EDJE_EXTERNAL_PARAM_TYPE_MAX = 5,
}
#[repr(C)]
pub struct EdjeExternalParam {
    pub name: *const c_char,
    pub _type: EdjeExternalParamType,
    pub i: c_int,
    pub d: c_double,
    pub s: *const c_char,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EdjeMessageType {
    EDJE_MESSAGE_NONE = 0,
    EDJE_MESSAGE_SIGNAL = 1,
    EDJE_MESSAGE_STRING = 2,
    EDJE_MESSAGE_INT = 3,
    EDJE_MESSAGE_FLOAT = 4,
    EDJE_MESSAGE_STRING_SET = 5,
    EDJE_MESSAGE_INT_SET = 6,
    EDJE_MESSAGE_FLOAT_SET = 7,
    EDJE_MESSAGE_STRING_INT = 8,
    EDJE_MESSAGE_STRING_FLOAT = 9,
    EDJE_MESSAGE_STRING_INT_SET = 10,
    EDJE_MESSAGE_STRING_FLOAT_SET = 11,
}
pub enum EdjePerspective { }
#[repr(C)]
pub struct EdjeVersion {
    pub major: c_int,
    pub minor: c_int,
    pub micro: c_int,
    pub revision: c_int,
}
pub type EdjeObject = Eo;
#[repr(C)]
pub struct EdjeColorClass {
    pub name: *const c_char,
    pub r: c_uchar,
    pub g: c_uchar,
    pub b: c_uchar,
    pub a: c_uchar,
    pub r2: c_uchar,
    pub g2: c_uchar,
    pub b2: c_uchar,
    pub a2: c_uchar,
    pub r3: c_uchar,
    pub g3: c_uchar,
    pub b3: c_uchar,
    pub a3: c_uchar,
    pub desc: *mut EinaStringshare,
}
pub type EdjeSignalCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                    obj: *mut EvasObject,
                                                    emission: *const c_char,
                                                    source: *const c_char)>;
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeExternalParamFlags {
    EDJE_EXTERNAL_PARAM_FLAGS_NONE = 0,
    EDJE_EXTERNAL_PARAM_FLAGS_GET = 1,
    EDJE_EXTERNAL_PARAM_FLAGS_SET = 2,
    EDJE_EXTERNAL_PARAM_FLAGS_STATE = 4,
    EDJE_EXTERNAL_PARAM_FLAGS_CONSTRUCTOR = 8,
    EDJE_EXTERNAL_PARAM_FLAGS_REGULAR = 7,
}
#[repr(C)]
pub struct EdjeExternalParamInfo {
    pub name: *const c_char,
    pub _type: EdjeExternalParamType,
    pub flags: EdjeExternalParamFlags,
    pub info: EdjeUnionUnnamed11,
}
#[repr(C)]
#[derive(Copy)]
pub struct EdjeUnionUnnamed11 {
    pub _bindgen_data_: [u64; 4usize],
}
impl EdjeUnionUnnamed11 {
    pub unsafe fn i(&mut self) -> *mut EdjeStructUnnamed12 {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn d(&mut self) -> *mut EdjeStructUnnamed13 {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn s(&mut self) -> *mut EdjeStructUnnamed14 {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn b(&mut self) -> *mut EdjeStructUnnamed15 {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn c(&mut self) -> *mut EdjeStructUnnamed16 {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
}
impl ::std::clone::Clone for EdjeUnionUnnamed11 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for EdjeUnionUnnamed11 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct EdjeStructUnnamed12 {
    pub def: c_int,
    pub min: c_int,
    pub max: c_int,
    pub step: c_int,
}
impl ::std::clone::Clone for EdjeStructUnnamed12 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for EdjeStructUnnamed12 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct EdjeStructUnnamed13 {
    pub def: c_double,
    pub min: c_double,
    pub max: c_double,
    pub step: c_double,
}
impl ::std::clone::Clone for EdjeStructUnnamed13 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for EdjeStructUnnamed13 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct EdjeStructUnnamed14 {
    pub def: *const c_char,
    pub accept_fmt: *const c_char,
    pub deny_fmt: *const c_char,
}
impl ::std::clone::Clone for EdjeStructUnnamed14 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for EdjeStructUnnamed14 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct EdjeStructUnnamed15 {
    pub def: c_int,
    pub false_str: *const c_char,
    pub true_str: *const c_char,
}
impl ::std::clone::Clone for EdjeStructUnnamed15 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for EdjeStructUnnamed15 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct EdjeStructUnnamed16 {
    pub def: *const c_char,
    pub choices: *mut *const c_char,
    pub def_get: Option<unsafe extern "C" fn(data: *mut c_void,
                                             info: *const EdjeExternalParamInfo)
                                           -> *mut c_char>,
    pub query: Option<unsafe extern "C" fn(data: *mut c_void,
                                           info: *const EdjeExternalParamInfo)
                                         -> *mut *mut c_char>,
}
impl ::std::clone::Clone for EdjeStructUnnamed16 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for EdjeStructUnnamed16 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
pub struct EdjeExternalType {
    pub abi_version: c_uint,
    pub module: *const c_char,
    pub module_name: *const c_char,
    pub add: Option<unsafe extern "C" fn(data: *mut c_void,
                                         evas: *mut Evas,
                                         parent: *mut EvasObject,
                                         params: *const EinaList,
                                         part_name: *const c_char)
                                       -> *mut EvasObject>,
    pub state_set: Option<unsafe extern "C" fn(data: *mut c_void,
                                               obj: *mut EvasObject,
                                               from_params: *const c_void,
                                               to_params: *const c_void,
                                               pos: c_float)>,
    pub signal_emit: Option<unsafe extern "C" fn(data: *mut c_void,
                                                 obj: *mut EvasObject,
                                                 emission: *const c_char,
                                                 source: *const c_char)>,
    pub param_set: Option<unsafe extern "C" fn(data: *mut c_void,
                                               obj: *mut EvasObject,
                                               param: *const EdjeExternalParam)
                                             -> EinaBool>,
    pub param_get: Option<unsafe extern "C" fn(data: *mut c_void,
                                               obj: *const EvasObject,
                                               param: *mut EdjeExternalParam)
                                             -> EinaBool>,
    pub content_get: Option<unsafe extern "C" fn(data: *mut c_void,
                                                 obj: *const EvasObject,
                                                 content: *const c_char)
                                               -> *mut EvasObject>,
    pub params_parse: Option<unsafe extern "C" fn(data: *mut c_void,
                                                  obj: *mut EvasObject,
                                                  params: *const EinaList)
                                                -> *mut c_void>,
    pub params_free: Option<unsafe extern "C" fn(params: *mut c_void)>,
    pub label_get: Option<unsafe extern "C" fn(data: *mut c_void)
                                             -> *const c_char>,
    pub description_get: Option<unsafe extern "C" fn(data: *mut c_void)
                                                   -> *const c_char>,
    pub icon_add: Option<unsafe extern "C" fn(data: *mut c_void,
                                              e: *mut Evas)
                                            -> *mut EvasObject>,
    pub preview_add: Option<unsafe extern "C" fn(data: *mut c_void,
                                                 e: *mut Evas)
                                               -> *mut EvasObject>,
    pub translate: Option<unsafe extern "C" fn(data: *mut c_void,
                                               orig: *const c_char)
                                             -> *const c_char>,
    pub parameters_info: *mut EdjeExternalParamInfo,
    pub data: *mut c_void,
}
#[repr(C)]
pub struct EdjeExternalTypeInfo {
    pub name: *const c_char,
    pub info: *const EdjeExternalType,
}
#[repr(C)]
pub struct EdjeEntryChangeInfo {
    pub change: EdjeUnionUnnamed17,
    pub _bindgen_bitfield_1_: EinaBool,
    pub _bindgen_bitfield_2_: EinaBool,
}
#[repr(C)]
pub struct EdjeUnionUnnamed17 {
    pub _bindgen_data_: [u64; 3usize],
}
impl EdjeUnionUnnamed17 {
    pub unsafe fn insert(&mut self) -> *mut EdjeStructUnnamed {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn del(&mut self) -> *mut EdjeStructUnnamed19 {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
}
impl ::std::clone::Clone for EdjeUnionUnnamed17 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for EdjeUnionUnnamed17 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct EdjeStructUnnamed {
    pub content: *const c_char,
    pub pos: size_t,
    pub plain_length: size_t,
}
impl ::std::clone::Clone for EdjeStructUnnamed {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for EdjeStructUnnamed {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct EdjeStructUnnamed19 {
    pub content: *const c_char,
    pub start: size_t,
    pub end: size_t,
}
impl ::std::clone::Clone for EdjeStructUnnamed19 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for EdjeStructUnnamed19 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeTextFilterType {
    EDJE_TEXT_FILTER_TEXT = 0,
    EDJE_TEXT_FILTER_FORMAT = 1,
    EDJE_TEXT_FILTER_MARKUP = 2,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeAnonEnum0 {
    EDJE_INPUT_PANEL_LAYOUT_NORMAL_VARIATION_NORMAL = 0,
    EDJE_INPUT_PANEL_LAYOUT_NORMAL_VARIATION_FILENAME = 1,
    EDJE_INPUT_PANEL_LAYOUT_NORMAL_VARIATION_PERSON_NAME = 2,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeAnonEnum1 {
    EDJE_INPUT_PANEL_LAYOUT_NUMBERONLY_VARIATION_NORMAL = 0,
    EDJE_INPUT_PANEL_LAYOUT_NUMBERONLY_VARIATION_SIGNED = 1,
    EDJE_INPUT_PANEL_LAYOUT_NUMBERONLY_VARIATION_DECIMAL = 2,
    EDJE_INPUT_PANEL_LAYOUT_NUMBERONLY_VARIATION_SIGNED_AND_DECIMAL = 3,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeAnonEnum2 {
    EDJE_INPUT_PANEL_LAYOUT_PASSWORD_VARIATION_NORMAL = 0,
    EDJE_INPUT_PANEL_LAYOUT_PASSWORD_VARIATION_NUMBERONLY = 1,
}
pub type EdjeTextFilterCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                        obj: *mut EvasObject,
                                                        part: *const c_char,
                                                        _type: EdjeTextFilterType,
                                                        text: *mut *mut c_char)>;
pub type EdjeMarkupFilterCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                          obj: *mut EvasObject,
                                                          part: *const c_char,
                                                          text: *mut *mut c_char)>;
pub type Edje_Item_Provider_Cb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                             obj: *mut EvasObject,
                                                             part: *const c_char,
                                                             item: *const c_char)
                              -> *mut EvasObject>;
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjePartType {
    EDJE_PART_TYPE_NONE = 0,
    EDJE_PART_TYPE_RECTANGLE = 1,
    EDJE_PART_TYPE_TEXT = 2,
    EDJE_PART_TYPE_IMAGE = 3,
    EDJE_PART_TYPE_SWALLOW = 4,
    EDJE_PART_TYPE_TEXTBLOCK = 5,
    EDJE_PART_TYPE_GRADIENT = 6,
    EDJE_PART_TYPE_GROUP = 7,
    EDJE_PART_TYPE_BOX = 8,
    EDJE_PART_TYPE_TABLE = 9,
    EDJE_PART_TYPE_EXTERNAL = 10,
    EDJE_PART_TYPE_PROXY = 11,
    EDJE_PART_TYPE_SPACER = 12,
    EDJE_PART_TYPE_MESH_NODE = 13,
    EDJE_PART_TYPE_LIGHT = 14,
    EDJE_PART_TYPE_CAMERA = 15,
    EDJE_PART_TYPE_SNAPSHOT = 16,
    EDJE_PART_TYPE_LAST = 17,
}
pub const EDJE_TEXT_EFFECT_SHADOW_DIRECTION_BOTTOM_RIGHT:
          EdjeTextEffect = EdjeTextEffect::EDJE_TEXT_EFFECT_NONE;
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeTextEffect {
    EDJE_TEXT_EFFECT_NONE = 0,
    EDJE_TEXT_EFFECT_PLAIN = 1,
    EDJE_TEXT_EFFECT_OUTLINE = 2,
    EDJE_TEXT_EFFECT_SOFT_OUTLINE = 3,
    EDJE_TEXT_EFFECT_SHADOW = 4,
    EDJE_TEXT_EFFECT_SOFT_SHADOW = 5,
    EDJE_TEXT_EFFECT_OUTLINE_SHADOW = 6,
    EDJE_TEXT_EFFECT_OUTLINE_SOFT_SHADOW = 7,
    EDJE_TEXT_EFFECT_FAR_SHADOW = 8,
    EDJE_TEXT_EFFECT_FAR_SOFT_SHADOW = 9,
    EDJE_TEXT_EFFECT_GLOW = 10,
    EDJE_TEXT_EFFECT_LAST = 11,
    EDJE_TEXT_EFFECT_SHADOW_DIRECTION_BOTTOM = 16,
    EDJE_TEXT_EFFECT_SHADOW_DIRECTION_BOTTOM_LEFT = 32,
    EDJE_TEXT_EFFECT_SHADOW_DIRECTION_LEFT = 48,
    EDJE_TEXT_EFFECT_SHADOW_DIRECTION_TOP_LEFT = 64,
    EDJE_TEXT_EFFECT_SHADOW_DIRECTION_TOP = 80,
    EDJE_TEXT_EFFECT_SHADOW_DIRECTION_TOP_RIGHT = 96,
    EDJE_TEXT_EFFECT_SHADOW_DIRECTION_RIGHT = 112,
}
pub type Edje_Text_Change_Cb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                           obj: *mut EvasObject,
                                                           part: *const c_char)>;
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeAspectControl {
    EDJE_ASPECT_CONTROL_NONE = 0,
    EDJE_ASPECT_CONTROL_NEITHER = 1,
    EDJE_ASPECT_CONTROL_HORIZONTAL = 2,
    EDJE_ASPECT_CONTROL_VERTICAL = 3,
    EDJE_ASPECT_CONTROL_BOTH = 4,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeObjectTableHomogeneousMode {
    EDJE_OBJECT_TABLE_HOMOGENEOUS_NONE = 0,
    EDJE_OBJECT_TABLE_HOMOGENEOUS_TABLE = 1,
    EDJE_OBJECT_TABLE_HOMOGENEOUS_ITEM = 2,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeTweenMode {
    EDJE_TWEEN_MODE_NONE = 0,
    EDJE_TWEEN_MODE_LINEAR = 1,
    EDJE_TWEEN_MODE_SINUSOIDAL = 2,
    EDJE_TWEEN_MODE_ACCELERATE = 3,
    EDJE_TWEEN_MODE_DECELERATE = 4,
    EDJE_TWEEN_MODE_ACCELERATE_FACTOR = 5,
    EDJE_TWEEN_MODE_DECELERATE_FACTOR = 6,
    EDJE_TWEEN_MODE_SINUSOIDAL_FACTOR = 7,
    EDJE_TWEEN_MODE_DIVISOR_INTERP = 8,
    EDJE_TWEEN_MODE_BOUNCE = 9,
    EDJE_TWEEN_MODE_SPRING = 10,
    EDJE_TWEEN_MODE_CUBIC_BEZIER = 11,
    EDJE_TWEEN_MODE_LAST = 12,
    EDJE_TWEEN_MODE_MASK = 255,
    EDJE_TWEEN_MODE_OPT_FROM_CURRENT = -2147483648,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeActionType {
    EDJE_ACTION_TYPE_NONE = 0,
    EDJE_ACTION_TYPE_STATE_SET = 1,
    EDJE_ACTION_TYPE_ACTION_STOP = 2,
    EDJE_ACTION_TYPE_SIGNAL_EMIT = 3,
    EDJE_ACTION_TYPE_DRAG_VAL_SET = 4,
    EDJE_ACTION_TYPE_DRAG_VAL_STEP = 5,
    EDJE_ACTION_TYPE_DRAG_VAL_PAGE = 6,
    EDJE_ACTION_TYPE_SCRIPT = 7,
    EDJE_ACTION_TYPE_FOCUS_SET = 8,
    EDJE_ACTION_TYPE_RESERVED00 = 9,
    EDJE_ACTION_TYPE_FOCUS_OBJECT = 10,
    EDJE_ACTION_TYPE_PARAM_COPY = 11,
    EDJE_ACTION_TYPE_PARAM_SET = 12,
    EDJE_ACTION_TYPE_SOUND_SAMPLE = 13,
    EDJE_ACTION_TYPE_SOUND_TONE = 14,
    EDJE_ACTION_TYPE_PHYSICS_IMPULSE = 15,
    EDJE_ACTION_TYPE_PHYSICS_TORQUE_IMPULSE = 16,
    EDJE_ACTION_TYPE_PHYSICS_FORCE = 17,
    EDJE_ACTION_TYPE_PHYSICS_TORQUE = 18,
    EDJE_ACTION_TYPE_PHYSICS_FORCES_CLEAR = 19,
    EDJE_ACTION_TYPE_PHYSICS_VEL_SET = 20,
    EDJE_ACTION_TYPE_PHYSICS_ANG_VEL_SET = 21,
    EDJE_ACTION_TYPE_PHYSICS_STOP = 22,
    EDJE_ACTION_TYPE_PHYSICS_ROT_SET = 23,
    EDJE_ACTION_TYPE_VIBRATION_SAMPLE = 24,
    EDJE_ACTION_TYPE_MO = 25,
    EDJE_ACTION_TYPE_LAST = 26,
}
#[repr(C)]
pub struct EdjeMessageString {
    pub _str: *mut c_char,
}
#[repr(C)]
pub struct EdjeMessageInt {
    pub val: c_int,
}
#[repr(C)]
pub struct EdjeMessageFloat {
    pub val: c_double,
}
#[repr(C)]
pub struct EdjeMessageStringSet {
    pub count: c_int,
    pub _str: [*mut c_char; 1usize],
}
#[repr(C)]
pub struct EdjeMessageIntSet {
    pub count: c_int,
    pub val: [c_int; 1usize],
}
#[repr(C)]
pub struct EdjeMessageFloatSet {
    pub count: c_int,
    pub val: [c_double; 1usize],
}
#[repr(C)]
pub struct EdjeMessageStringInt {
    pub _str: *mut c_char,
    pub val: c_int,
}
#[repr(C)]
pub struct EdjeMessageStringFloat {
    pub _str: *mut c_char,
    pub val: c_double,
}
#[repr(C)]
pub struct EdjeMessageStringIntSet {
    pub _str: *mut c_char,
    pub count: c_int,
    pub val: [c_int; 1usize],
}
#[repr(C)]
pub struct EdjeMessageStringFloatSet {
    pub _str: *mut c_char,
    pub count: c_int,
    pub val: [c_double; 1usize],
}
pub type EdjeMessageHandlerCb = Option<unsafe extern "C" fn(data: *mut c_void,
                                                            obj: *mut EvasObject,
                                                            _type: EdjeMessageType,
                                                            id: c_int,
                                                            msg: *mut c_void)>;
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum EdjeChannel {
    EDJE_CHANNEL_EFFECT = 0,
    EDJE_CHANNEL_BACKGROUND = 1,
    EDJE_CHANNEL_MUSIC = 2,
    EDJE_CHANNEL_FOREGROUND = 3,
    EDJE_CHANNEL_INTERFACE = 4,
    EDJE_CHANNEL_INPUT = 5,
    EDJE_CHANNEL_ALERT = 6,
    EDJE_CHANNEL_ALL = 7,
}
pub type EdjeEdit = Eo;

#[link(name = "edje")]
extern "C" {
    pub static mut edje_version: *mut EdjeVersion;
    pub static _EDJE_OBJECT_EVENT_RECALC: EoEventDescription;
}
#[link(name = "edje")]
extern "C" {
    pub fn edje_object_signal_callback_extra_data_get()
     -> *mut c_void;
    pub fn edje_init() -> c_int;
    pub fn edje_shutdown() -> c_int;
    pub fn edje_fontset_append_set(fonts: *const c_char);
    pub fn edje_mmap_data_get(f: *const EinaFile,
                              key: *const c_char)
     -> *mut c_char;
    pub fn edje_file_data_get(file: *const c_char,
                              key: *const c_char)
     -> *mut c_char;
    pub fn edje_module_load(module: *const c_char)
     -> EinaBool;
    pub fn edje_available_modules_get() -> *const EinaList;
    pub fn edje_fontset_append_get() -> *const c_char;
    pub fn edje_file_cache_set(count: c_int);
    pub fn edje_file_cache_get() -> c_int;
    pub fn edje_file_cache_flush();
    pub fn edje_collection_cache_set(count: c_int);
    pub fn edje_collection_cache_get() -> c_int;
    pub fn edje_collection_cache_flush();
    pub fn edje_external_param_type_str(_type: EdjeExternalParamType)
     -> *const c_char;
    pub fn edje_external_type_register(type_name:
                                           *const c_char,
                                       type_info: *const EdjeExternalType)
     -> EinaBool;
    pub fn edje_external_type_unregister(type_name:
                                             *const c_char)
     -> EinaBool;
    pub fn edje_external_type_array_register(array:
                                                 *const EdjeExternalTypeInfo);
    pub fn edje_external_type_array_unregister(array:
                                                   *const EdjeExternalTypeInfo);
    pub fn edje_external_type_abi_version_get() -> c_uint;
    pub fn edje_external_iterator_get() -> *mut EinaIterator;
    pub fn edje_external_param_find(params: *const EinaList,
                                    key: *const c_char)
     -> *mut EdjeExternalParam;
    pub fn edje_external_param_int_get(params: *const EinaList,
                                       key: *const c_char,
                                       ret: *mut c_int)
     -> EinaBool;
    pub fn edje_external_param_double_get(params: *const EinaList,
                                          key: *const c_char,
                                          ret: *mut c_double)
     -> EinaBool;
    pub fn edje_external_param_string_get(params: *const EinaList,
                                          key: *const c_char,
                                          ret:
                                              *mut *const c_char)
     -> EinaBool;
    pub fn edje_external_param_bool_get(params: *const EinaList,
                                        key: *const c_char,
                                        ret: *mut EinaBool) -> EinaBool;
    pub fn edje_external_param_choice_get(params: *const EinaList,
                                          key: *const c_char,
                                          ret:
                                              *mut *const c_char)
     -> EinaBool;
    pub fn edje_external_param_info_get(type_name:
                                            *const c_char)
     -> *const EdjeExternalParamInfo;
    pub fn edje_external_type_get(type_name: *const c_char)
     -> *const EdjeExternalType;
    pub fn edje_scale_set(scale: c_double);
    pub fn edje_scale_get() -> c_double;
    pub fn edje_password_show_last_set(password_show_last: EinaBool);
    pub fn edje_password_show_last_timeout_set(password_show_last_timeout:
                                                   c_double);
    pub fn edje_color_class_set(color_class: *const c_char,
                                r: c_int,
                                g: c_int,
                                b: c_int,
                                a: c_int,
                                r2: c_int,
                                g2: c_int,
                                b2: c_int,
                                a2: c_int,
                                r3: c_int,
                                g3: c_int,
                                b3: c_int,
                                a3: c_int) -> EinaBool;
    pub fn edje_color_class_get(color_class: *const c_char,
                                r: *mut c_int,
                                g: *mut c_int,
                                b: *mut c_int,
                                a: *mut c_int,
                                r2: *mut c_int,
                                g2: *mut c_int,
                                b2: *mut c_int,
                                a2: *mut c_int,
                                r3: *mut c_int,
                                g3: *mut c_int,
                                b3: *mut c_int,
                                a3: *mut c_int) -> EinaBool;
    pub fn edje_color_class_del(color_class: *const c_char);
    pub fn edje_color_class_list() -> *mut EinaList;
    pub fn edje_color_class_active_iterator_new() -> *mut EinaIterator;
    pub fn edje_mmap_color_class_iterator_new(f: *mut EinaFile)
     -> *mut EinaIterator;
    pub fn edje_box_layout_register(name: *const c_char,
                                    func: EvasObject_Box_Layout,
                                    layout_data_get:
                                        Option<unsafe extern "C" fn(arg1:
                                                                                       *mut c_void)
                                                                  ->
                                                                      *mut c_void>,
                                    layout_data_free:
                                        Option<unsafe extern "C" fn(arg1:
                                                                                       *mut c_void)>,
                                    free_data:
                                        Option<unsafe extern "C" fn(arg1:
                                                                                       *mut c_void)>,
                                    data: *mut c_void);
    pub fn edje_text_class_set(text_class: *const c_char,
                               font: *const c_char,
                               size: EvasFontSize) -> EinaBool;
    pub fn edje_text_class_get(text_class: *const c_char,
                               font: *mut *const c_char,
                               size: *mut EvasFontSize) -> EinaBool;
    pub fn edje_text_class_del(text_class: *const c_char);
    pub fn edje_text_class_list() -> *mut EinaList;
    pub fn edje_mmap_collection_list(f: *mut EinaFile) -> *mut EinaList;
    pub fn edje_mmap_collection_list_free(lst: *mut EinaList);
    pub fn edje_mmap_group_exists(f: *mut EinaFile,
                                  glob: *const c_char)
     -> EinaBool;
    pub fn edje_file_iterator_new() -> *mut EinaIterator;
    pub fn edje_file_collection_list(file: *const c_char)
     -> *mut EinaList;
    pub fn edje_file_collection_list_free(lst: *mut EinaList);
    pub fn edje_file_group_exists(file: *const c_char,
                                  glob: *const c_char)
     -> EinaBool;
    pub fn edje_load_error_str(error: EdjeLoadError)
     -> *const c_char;
    pub fn edje_frametime_set(t: c_double);
    pub fn edje_frametime_get() -> c_double;
    pub fn edje_freeze();
    pub fn edje_thaw();
    pub fn edje_language_set(locale: *const c_char);
    pub fn edje_transition_duration_factor_set(scale:
                                                   c_double);
    pub fn edje_transition_duration_factor_get() -> c_double;
    pub fn edje_message_signal_process();
    pub fn edje_perspective_new(e: *mut Evas) -> *mut EdjePerspective;
    pub fn edje_perspective_free(ps: *mut EdjePerspective);
    pub fn edje_perspective_set(ps: *mut EdjePerspective, px: EvasCoord,
                                py: EvasCoord, z0: EvasCoord,
                                foc: EvasCoord);
    pub fn edje_perspective_global_set(ps: *mut EdjePerspective,
                                       global: EinaBool);
    pub fn edje_perspective_global_get(ps: *const EdjePerspective)
     -> EinaBool;
    pub fn edje_evas_global_perspective_get(e: *const Evas)
     -> *const EdjePerspective;
    pub fn edje_audio_channel_mute_set(channel: EdjeChannel,
                                       mute: EinaBool);
    pub fn edje_audio_channel_mute_get(channel: EdjeChannel) -> EinaBool;
    pub fn edje_object_part_object_name_get(obj: *const EvasObject)
     -> *const c_char;
    pub fn edje_object_add(evas: *mut Evas) -> *mut EvasObject;
    pub fn edje_object_signal_callback_del(obj: *mut EvasObject,
                                           emission:
                                               *const c_char,
                                           source:
                                               *const c_char,
                                           func: EdjeSignalCb)
     -> *mut c_void;
    pub fn edje_object_signal_callback_del_full(obj: *mut EvasObject,
                                                emission:
                                                    *const c_char,
                                                source:
                                                    *const c_char,
                                                func: EdjeSignalCb,
                                                data:
                                                    *mut c_void)
     -> *mut c_void;
    pub fn edje_object_color_class_del(obj: *mut EvasObject,
                                       color_class:
                                           *const c_char);
    pub fn edje_extern_object_min_size_set(obj: *mut EvasObject,
                                           minw: EvasCoord,
                                           minh: EvasCoord);
    pub fn edje_extern_object_max_size_set(obj: *mut EvasObject,
                                           maxw: EvasCoord,
                                           maxh: EvasCoord);
    pub fn edje_extern_object_aspect_set(obj: *mut EvasObject,
                                         aspect: EdjeAspectControl,
                                         aw: EvasCoord, ah: EvasCoord);
    pub fn edje_object_file_set(obj: *mut EdjeObject,
                                file: *const c_char,
                                group: *const c_char)
     -> EinaBool;
    pub fn edje_object_file_get(obj: *const EdjeObject,
                                file: *mut *const c_char,
                                group: *mut *const c_char);
    pub fn edje_object_mmap_set(obj: *mut EdjeObject, file: *const EinaFile,
                                group: *const c_char)
     -> EinaBool;
    pub fn edje_object_update_hints_set(obj: *mut EdjeObject,
                                        update: EinaBool);
    pub fn edje_object_update_hints_get(obj: *const EdjeObject) -> EinaBool;
    pub fn edje_object_mirrored_set(obj: *mut EdjeObject, rtl: EinaBool);
    pub fn edje_object_mirrored_get(obj: *const EdjeObject) -> EinaBool;
    pub fn edje_object_language_set(obj: *mut EdjeObject,
                                    language: *const c_char);
    pub fn edje_object_language_get(obj: *const EdjeObject)
     -> *const c_char;
    pub fn edje_object_animation_set(obj: *mut EdjeObject, on: EinaBool);
    pub fn edje_object_animation_get(obj: *const EdjeObject) -> EinaBool;
    pub fn edje_object_play_set(obj: *mut EdjeObject, play: EinaBool);
    pub fn edje_object_play_get(obj: *const EdjeObject) -> EinaBool;
    pub fn edje_object_perspective_set(obj: *mut EdjeObject,
                                       ps: *mut EdjePerspective);
    pub fn edje_object_perspective_get(obj: *const EdjeObject)
     -> *const EdjePerspective;
    pub fn edje_object_scale_set(obj: *mut EdjeObject,
                                 scale: c_double)
     -> EinaBool;
    pub fn edje_object_scale_get(obj: *const EdjeObject)
     -> c_double;
    pub fn edje_object_base_scale_get(obj: *const EdjeObject)
     -> c_double;
    pub fn edje_object_text_change_cb_set(obj: *mut EdjeObject,
                                          func: Edje_Text_Change_Cb,
                                          data: *mut c_void);
    pub fn edje_object_part_text_cursor_begin_set(obj: *mut EdjeObject,
                                                  part:
                                                      *const c_char,
                                                  cur: EdjeCursor);
    pub fn edje_object_part_text_cursor_line_end_set(obj: *mut EdjeObject,
                                                     part:
                                                         *const c_char,
                                                     cur: EdjeCursor);
    pub fn edje_object_text_class_set(obj: *mut EdjeObject,
                                      text_class:
                                          *const c_char,
                                      font: *const c_char,
                                      size: EvasFontSize) -> EinaBool;
    pub fn edje_object_part_text_cursor_coord_set(obj: *mut EdjeObject,
                                                  part:
                                                      *const c_char,
                                                  cur: EdjeCursor,
                                                  x: EvasCoord,
                                                  y: EvasCoord) -> EinaBool;
    pub fn edje_object_part_text_cursor_end_set(obj: *mut EdjeObject,
                                                part:
                                                    *const c_char,
                                                cur: EdjeCursor);
    pub fn edje_object_part_text_escaped_set(obj: *mut EdjeObject,
                                             part:
                                                 *const c_char,
                                             text:
                                                 *const c_char)
     -> EinaBool;
    pub fn edje_object_item_provider_set(obj: *mut EdjeObject,
                                         func: Edje_Item_Provider_Cb,
                                         data: *mut c_void);
    pub fn edje_object_part_text_cursor_line_begin_set(obj: *mut EdjeObject,
                                                       part:
                                                           *const c_char,
                                                       cur: EdjeCursor);
    pub fn edje_object_message_handler_set(obj: *mut EdjeObject,
                                           func: EdjeMessageHandlerCb,
                                           data: *mut c_void);
    pub fn edje_object_size_min_get(obj: *const EdjeObject,
                                    minw: *mut EvasCoord,
                                    minh: *mut EvasCoord);
    pub fn edje_object_access_part_list_get(obj: *const EdjeObject)
     -> *mut EinaList;
    pub fn edje_object_load_error_get(obj: *const EdjeObject)
     -> EdjeLoadError;
    pub fn edje_object_size_max_get(obj: *const EdjeObject,
                                    maxw: *mut EvasCoord,
                                    maxh: *mut EvasCoord);
    pub fn edje_object_transition_duration_factor_set(obj: *mut EdjeObject,
                                                      scale:
                                                          c_double);
    pub fn edje_object_transition_duration_factor_get(obj: *const EdjeObject)
     -> c_double;
    pub fn edje_object_part_table_clear(obj: *mut EdjeObject,
                                        part: *const c_char,
                                        clear: EinaBool) -> EinaBool;
    pub fn edje_object_part_external_param_type_get(obj: *const EdjeObject,
                                                    part:
                                                        *const c_char,
                                                    param:
                                                        *const c_char)
     -> EdjeExternalParamType;
    pub fn edje_object_part_text_select_allow_set(obj: *const EdjeObject,
                                                  part:
                                                      *const c_char,
                                                  allow: EinaBool);
    pub fn edje_object_part_state_get(obj: *const EdjeObject,
                                      part: *const c_char,
                                      val_ret: *mut c_double)
     -> *const c_char;
    pub fn edje_object_text_markup_filter_callback_del_full(obj:
                                                                *mut EdjeObject,
                                                            part:
                                                                *const c_char,
                                                            func:
                                                                EdjeMarkupFilterCb,
                                                            data:
                                                                *mut c_void)
     -> *mut c_void;
    pub fn edje_object_part_drag_step_set(obj: *mut EdjeObject,
                                          part: *const c_char,
                                          dx: c_double,
                                          dy: c_double)
     -> EinaBool;
    pub fn edje_object_part_drag_step_get(obj: *const EdjeObject,
                                          part: *const c_char,
                                          dx: *mut c_double,
                                          dy: *mut c_double)
     -> EinaBool;
    pub fn edje_object_part_text_imf_context_get(obj: *const EdjeObject,
                                                 part:
                                                     *const c_char)
     -> *mut c_void;
    pub fn edje_object_part_text_select_begin(obj: *const EdjeObject,
                                              part:
                                                  *const c_char);
    pub fn edje_object_part_text_style_user_peek(obj: *const EdjeObject,
                                                 part:
                                                     *const c_char)
     -> *const c_char;
    pub fn edje_object_part_text_cursor_next(obj: *mut EdjeObject,
                                             part:
                                                 *const c_char,
                                             cur: EdjeCursor) -> EinaBool;
    pub fn edje_object_part_text_style_user_push(obj: *mut EdjeObject,
                                                 part:
                                                     *const c_char,
                                                 style:
                                                     *const c_char);
    pub fn edje_object_part_text_append(obj: *mut EdjeObject,
                                        part: *const c_char,
                                        text: *const c_char);
    pub fn edje_object_part_geometry_get(obj: *const EdjeObject,
                                         part: *const c_char,
                                         x: *mut EvasCoord,
                                         y: *mut EvasCoord,
                                         w: *mut EvasCoord,
                                         h: *mut EvasCoord) -> EinaBool;
    pub fn edje_object_part_text_input_panel_hide(obj: *const EdjeObject,
                                                  part:
                                                      *const c_char);
    pub fn edje_object_part_text_item_geometry_get(obj: *const EdjeObject,
                                                   part:
                                                       *const c_char,
                                                   item:
                                                       *const c_char,
                                                   cx: *mut EvasCoord,
                                                   cy: *mut EvasCoord,
                                                   cw: *mut EvasCoord,
                                                   ch: *mut EvasCoord)
     -> EinaBool;
    pub fn edje_object_part_table_unpack(obj: *mut EdjeObject,
                                         part: *const c_char,
                                         child_obj: *mut EvasObject)
     -> EinaBool;
    pub fn edje_object_part_text_select_abort(obj: *const EdjeObject,
                                              part:
                                                  *const c_char);
    pub fn edje_object_text_insert_filter_callback_del_full(obj:
                                                                *mut EdjeObject,
                                                            part:
                                                                *const c_char,
                                                            func:
                                                                EdjeTextFilterCb,
                                                            data:
                                                                *mut c_void)
     -> *mut c_void;
    pub fn edje_object_part_text_style_user_pop(obj: *mut EdjeObject,
                                                part:
                                                    *const c_char);
    pub fn edje_object_part_text_input_panel_imdata_set(obj: *mut EdjeObject,
                                                        part:
                                                            *const c_char,
                                                        data:
                                                            *const c_void,
                                                        len:
                                                            c_int);
    pub fn edje_object_part_text_input_panel_imdata_get(obj:
                                                            *const EdjeObject,
                                                        part:
                                                            *const c_char,
                                                        data:
                                                            *mut c_void,
                                                        len:
                                                            *mut c_int);
    pub fn edje_object_part_text_insert(obj: *mut EdjeObject,
                                        part: *const c_char,
                                        text: *const c_char);
    pub fn edje_object_part_box_remove_at(obj: *mut EdjeObject,
                                          part: *const c_char,
                                          pos: c_uint)
     -> *mut EvasObject;
    pub fn edje_object_part_text_cursor_copy(obj: *mut EdjeObject,
                                             part:
                                                 *const c_char,
                                             src: EdjeCursor,
                                             dst: EdjeCursor);
    pub fn edje_object_parts_extends_calc(obj: *mut EdjeObject,
                                          x: *mut EvasCoord,
                                          y: *mut EvasCoord,
                                          w: *mut EvasCoord,
                                          h: *mut EvasCoord) -> EinaBool;
    pub fn edje_object_part_drag_value_set(obj: *mut EdjeObject,
                                           part:
                                               *const c_char,
                                           dx: c_double,
                                           dy: c_double)
     -> EinaBool;
    pub fn edje_object_part_drag_value_get(obj: *const EdjeObject,
                                           part:
                                               *const c_char,
                                           dx: *mut c_double,
                                           dy: *mut c_double)
     -> EinaBool;
    pub fn edje_object_calc_force(obj: *mut EdjeObject);
    pub fn edje_object_part_text_cursor_pos_set(obj: *mut EdjeObject,
                                                part:
                                                    *const c_char,
                                                cur: EdjeCursor,
                                                pos: c_int);
    pub fn edje_object_part_text_cursor_pos_get(obj: *const EdjeObject,
                                                part:
                                                    *const c_char,
                                                cur: EdjeCursor)
     -> c_int;
    pub fn edje_object_freeze(obj: *mut EdjeObject) -> c_int;
    pub fn edje_object_part_text_cursor_content_get(obj: *const EdjeObject,
                                                    part:
                                                        *const c_char,
                                                    cur: EdjeCursor)
     -> *mut c_char;
    pub fn edje_object_part_text_input_panel_layout_set(obj: *mut EdjeObject,
                                                        part:
                                                            *const c_char,
                                                        layout:
                                                            EdjeInputPanelLayout);
    pub fn edje_object_part_text_input_panel_layout_get(obj:
                                                            *const EdjeObject,
                                                        part:
                                                            *const c_char)
     -> EdjeInputPanelLayout;
    pub fn edje_object_part_table_pack(obj: *mut EdjeObject,
                                       part: *const c_char,
                                       child_obj: *mut EvasObject,
                                       col: c_ushort,
                                       row: c_ushort,
                                       colspan: c_ushort,
                                       rowspan: c_ushort)
     -> EinaBool;
    pub fn edje_object_part_text_input_panel_language_set(obj:
                                                              *mut EdjeObject,
                                                          part:
                                                              *const c_char,
                                                          lang:
                                                              EdjeInputPanelLang);
    pub fn edje_object_part_text_input_panel_language_get(obj:
                                                              *const EdjeObject,
                                                          part:
                                                              *const c_char)
     -> EdjeInputPanelLang;
    pub fn edje_object_part_table_col_row_size_get(obj: *const EdjeObject,
                                                   part:
                                                       *const c_char,
                                                   cols:
                                                       *mut c_int,
                                                   rows:
                                                       *mut c_int)
     -> EinaBool;
    pub fn edje_object_part_external_object_get(obj: *const EdjeObject,
                                                part:
                                                    *const c_char)
     -> *mut EvasObject;
    pub fn edje_object_part_external_content_get(obj: *const EdjeObject,
                                                 part:
                                                     *const c_char,
                                                 content:
                                                     *const c_char)
     -> *mut EvasObject;
    pub fn edje_object_preload(obj: *mut EdjeObject, cancel: EinaBool)
     -> EinaBool;
    pub fn edje_object_part_text_input_panel_enabled_set(obj:
                                                             *mut EdjeObject,
                                                         part:
                                                             *const c_char,
                                                         enabled: EinaBool);
    pub fn edje_object_part_text_input_panel_enabled_get(obj:
                                                             *const EdjeObject,
                                                         part:
                                                             *const c_char)
     -> EinaBool;
    pub fn edje_object_part_text_select_extend(obj: *const EdjeObject,
                                               part:
                                                   *const c_char);
    pub fn edje_object_part_box_insert_at(obj: *mut EdjeObject,
                                          part: *const c_char,
                                          child: *mut EvasObject,
                                          pos: c_uint)
     -> EinaBool;
    pub fn edje_object_part_text_anchor_geometry_get(obj: *const EdjeObject,
                                                     part:
                                                         *const c_char,
                                                     anchor:
                                                         *const c_char)
     -> *const EinaList;
    pub fn edje_object_part_text_cursor_down(obj: *mut EdjeObject,
                                             part:
                                                 *const c_char,
                                             cur: EdjeCursor) -> EinaBool;
    pub fn edje_object_part_drag_page_set(obj: *mut EdjeObject,
                                          part: *const c_char,
                                          dx: c_double,
                                          dy: c_double)
     -> EinaBool;
    pub fn edje_object_part_drag_page_get(obj: *const EdjeObject,
                                          part: *const c_char,
                                          dx: *mut c_double,
                                          dy: *mut c_double)
     -> EinaBool;
    pub fn edje_object_part_box_prepend(obj: *mut EdjeObject,
                                        part: *const c_char,
                                        child: *mut EvasObject) -> EinaBool;
    pub fn edje_object_signal_emit(obj: *mut EdjeObject,
                                   emission: *const c_char,
                                   source: *const c_char);
    pub fn edje_object_part_text_input_panel_layout_variation_set(obj:
                                                                      *mut EdjeObject,
                                                                  part:
                                                                      *const c_char,
                                                                  variation:
                                                                      c_int);
    pub fn edje_object_part_text_input_panel_layout_variation_get(obj:
                                                                      *const EdjeObject,
                                                                  part:
                                                                      *const c_char)
     -> c_int;
    pub fn edje_object_message_send(obj: *mut EdjeObject,
                                    _type: EdjeMessageType,
                                    id: c_int,
                                    msg: *mut c_void);
    pub fn edje_object_part_text_select_none(obj: *const EdjeObject,
                                             part:
                                                 *const c_char);
    pub fn edje_object_part_object_get(obj: *const EdjeObject,
                                       part: *const c_char)
     -> *const EvasObject;
    pub fn edje_object_part_drag_size_set(obj: *mut EdjeObject,
                                          part: *const c_char,
                                          dw: c_double,
                                          dh: c_double)
     -> EinaBool;
    pub fn edje_object_part_drag_size_get(obj: *const EdjeObject,
                                          part: *const c_char,
                                          dw: *mut c_double,
                                          dh: *mut c_double)
     -> EinaBool;
    pub fn edje_object_text_insert_filter_callback_del(obj: *mut EdjeObject,
                                                       part:
                                                           *const c_char,
                                                       func:
                                                           EdjeTextFilterCb)
     -> *mut c_void;
    pub fn edje_object_part_drag_dir_get(obj: *const EdjeObject,
                                         part: *const c_char)
     -> EdjeDragDir;
    pub fn edje_object_part_text_unescaped_set(obj: *mut EdjeObject,
                                               part:
                                                   *const c_char,
                                               text_to_escape:
                                                   *const c_char)
     -> EinaBool;
    pub fn edje_object_part_text_unescaped_get(obj: *const EdjeObject,
                                               part:
                                                   *const c_char)
     -> *mut c_char;
    pub fn edje_object_signal_callback_add(obj: *mut EdjeObject,
                                           emission:
                                               *const c_char,
                                           source:
                                               *const c_char,
                                           func: EdjeSignalCb,
                                           data: *mut c_void);
    pub fn edje_object_part_text_select_all(obj: *const EdjeObject,
                                            part:
                                                *const c_char);
    pub fn edje_object_part_text_input_panel_return_key_disabled_set(obj:
                                                                         *mut EdjeObject,
                                                                     part:
                                                                         *const c_char,
                                                                     disabled:
                                                                         EinaBool);
    pub fn edje_object_part_text_input_panel_return_key_disabled_get(obj:
                                                                         *const EdjeObject,
                                                                     part:
                                                                         *const c_char)
     -> EinaBool;
    pub fn edje_object_part_text_autocapital_type_set(obj: *mut EdjeObject,
                                                      part:
                                                          *const c_char,
                                                      autocapital_type:
                                                          EdjeTextAutocapitalType);
    pub fn edje_object_part_text_autocapital_type_get(obj: *const EdjeObject,
                                                      part:
                                                          *const c_char)
     -> EdjeTextAutocapitalType;
    pub fn edje_object_part_unswallow(obj: *mut EdjeObject,
                                      obj_swallow: *mut EvasObject);
    pub fn edje_object_part_text_prediction_allow_set(obj: *mut EdjeObject,
                                                      part:
                                                          *const c_char,
                                                      prediction: EinaBool);
    pub fn edje_object_part_text_prediction_allow_get(obj: *const EdjeObject,
                                                      part:
                                                          *const c_char)
     -> EinaBool;
    pub fn edje_object_data_get(obj: *const EdjeObject,
                                key: *const c_char)
     -> *const c_char;
    pub fn edje_object_text_markup_filter_callback_add(obj: *mut EdjeObject,
                                                       part:
                                                           *const c_char,
                                                       func:
                                                           EdjeMarkupFilterCb,
                                                       data:
                                                           *mut c_void);
    pub fn edje_object_message_signal_process(obj: *mut EdjeObject);
    pub fn edje_object_part_box_remove(obj: *mut EdjeObject,
                                       part: *const c_char,
                                       child: *mut EvasObject)
     -> *mut EvasObject;
    pub fn edje_object_thaw(obj: *mut EdjeObject) -> c_int;
    pub fn edje_object_part_swallow_get(obj: *const EdjeObject,
                                        part: *const c_char)
     -> *mut EvasObject;
    pub fn edje_object_part_text_imf_context_reset(obj: *const EdjeObject,
                                                   part:
                                                       *const c_char);
    pub fn edje_object_part_text_input_panel_return_key_type_set(obj:
                                                                     *mut EdjeObject,
                                                                 part:
                                                                     *const c_char,
                                                                 return_key_type:
                                                                     EdjeInputPanelReturnKeyType);
    pub fn edje_object_part_text_input_panel_return_key_type_get(obj:
                                                                     *const EdjeObject,
                                                                 part:
                                                                     *const c_char)
     -> EdjeInputPanelReturnKeyType;
    pub fn edje_object_part_table_child_get(obj: *const EdjeObject,
                                            part:
                                                *const c_char,
                                            col: c_uint,
                                            row: c_uint)
     -> *mut EvasObject;
    pub fn edje_object_part_box_insert_before(obj: *mut EdjeObject,
                                              part:
                                                  *const c_char,
                                              child: *mut EvasObject,
                                              reference: *const EvasObject)
     -> EinaBool;
    pub fn edje_object_part_external_param_set(obj: *mut EdjeObject,
                                               part:
                                                   *const c_char,
                                               param:
                                                   *const EdjeExternalParam)
     -> EinaBool;
    pub fn edje_object_part_external_param_get(obj: *const EdjeObject,
                                               part:
                                                   *const c_char,
                                               param:
                                                   *mut EdjeExternalParam)
     -> EinaBool;
    pub fn edje_object_size_min_calc(obj: *mut EdjeObject,
                                     minw: *mut EvasCoord,
                                     minh: *mut EvasCoord);
    pub fn edje_object_part_box_append(obj: *mut EdjeObject,
                                       part: *const c_char,
                                       child: *mut EvasObject) -> EinaBool;
    pub fn edje_object_size_min_restricted_calc(obj: *mut EdjeObject,
                                                minw: *mut EvasCoord,
                                                minh: *mut EvasCoord,
                                                restrictedw: EvasCoord,
                                                restrictedh: EvasCoord);
    pub fn edje_object_part_box_remove_all(obj: *mut EdjeObject,
                                           part:
                                               *const c_char,
                                           clear: EinaBool) -> EinaBool;
    pub fn edje_object_part_drag_page(obj: *mut EdjeObject,
                                      part: *const c_char,
                                      dx: c_double,
                                      dy: c_double)
     -> EinaBool;
    pub fn edje_object_part_text_set(obj: *mut EdjeObject,
                                     part: *const c_char,
                                     text: *const c_char)
     -> EinaBool;
    pub fn edje_object_part_text_get(obj: *const EdjeObject,
                                     part: *const c_char)
     -> *const c_char;
    pub fn edje_object_part_text_input_panel_show_on_demand_set(obj:
                                                                    *mut EdjeObject,
                                                                part:
                                                                    *const c_char,
                                                                ondemand:
                                                                    EinaBool);
    pub fn edje_object_part_text_input_panel_show_on_demand_get(obj:
                                                                    *const EdjeObject,
                                                                part:
                                                                    *const c_char)
     -> EinaBool;
    pub fn edje_object_part_text_input_hint_set(obj: *mut EdjeObject,
                                                part:
                                                    *const c_char,
                                                input_hints:
                                                    EdjeInputHints);
    pub fn edje_object_part_text_input_hint_get(obj: *const EdjeObject,
                                                part:
                                                    *const c_char)
     -> EdjeInputHints;
    pub fn edje_object_part_text_selection_get(obj: *const EdjeObject,
                                               part:
                                                   *const c_char)
     -> *const c_char;
    pub fn edje_object_part_text_cursor_is_format_get(obj: *const EdjeObject,
                                                      part:
                                                          *const c_char,
                                                      cur: EdjeCursor)
     -> EinaBool;
    pub fn edje_object_text_class_get(obj: *const EdjeObject,
                                      text_class:
                                          *const c_char,
                                      font:
                                          *mut *const c_char,
                                      size: *mut EvasFontSize) -> EinaBool;
    pub fn edje_object_color_class_set(obj: *mut EdjeObject,
                                       color_class:
                                           *const c_char,
                                       r: c_int,
                                       g: c_int,
                                       b: c_int,
                                       a: c_int,
                                       r2: c_int,
                                       g2: c_int,
                                       b2: c_int,
                                       a2: c_int,
                                       r3: c_int,
                                       g3: c_int,
                                       b3: c_int,
                                       a3: c_int)
     -> EinaBool;
    pub fn edje_object_color_class_get(obj: *const EdjeObject,
                                       color_class:
                                           *const c_char,
                                       r: *mut c_int,
                                       g: *mut c_int,
                                       b: *mut c_int,
                                       a: *mut c_int,
                                       r2: *mut c_int,
                                       g2: *mut c_int,
                                       b2: *mut c_int,
                                       a2: *mut c_int,
                                       r3: *mut c_int,
                                       g3: *mut c_int,
                                       b3: *mut c_int,
                                       a3: *mut c_int)
     -> EinaBool;
    pub fn edje_object_color_class_description_get(obj: *const EdjeObject,
                                                   color_class:
                                                       *const c_char)
     -> *const c_char;
    pub fn edje_object_part_drag_step(obj: *mut EdjeObject,
                                      part: *const c_char,
                                      dx: c_double,
                                      dy: c_double)
     -> EinaBool;
    pub fn edje_object_part_text_cursor_up(obj: *mut EdjeObject,
                                           part:
                                               *const c_char,
                                           cur: EdjeCursor) -> EinaBool;
    pub fn edje_object_part_text_cursor_geometry_get(obj: *const EdjeObject,
                                                     part:
                                                         *const c_char,
                                                     x: *mut EvasCoord,
                                                     y: *mut EvasCoord,
                                                     w: *mut EvasCoord,
                                                     h: *mut EvasCoord);
    pub fn edje_object_part_text_anchor_list_get(obj: *const EdjeObject,
                                                 part:
                                                     *const c_char)
     -> *const EinaList;
    pub fn edje_object_text_insert_filter_callback_add(obj: *mut EdjeObject,
                                                       part:
                                                           *const c_char,
                                                       func:
                                                           EdjeTextFilterCb,
                                                       data:
                                                           *mut c_void);
    pub fn edje_object_part_text_input_panel_show(obj: *const EdjeObject,
                                                  part:
                                                      *const c_char);
    pub fn edje_object_part_exists(obj: *const EdjeObject,
                                   part: *const c_char)
     -> EinaBool;
    pub fn edje_object_text_markup_filter_callback_del(obj: *mut EdjeObject,
                                                       part:
                                                           *const c_char,
                                                       func:
                                                           EdjeMarkupFilterCb)
     -> *mut c_void;
    pub fn edje_object_part_text_cursor_is_visible_format_get(obj:
                                                                  *const EdjeObject,
                                                              part:
                                                                  *const c_char,
                                                              cur:
                                                                  EdjeCursor)
     -> EinaBool;
    pub fn edje_object_part_text_user_insert(obj: *const EdjeObject,
                                             part:
                                                 *const c_char,
                                             text:
                                                 *const c_char);
    pub fn edje_object_part_text_cursor_prev(obj: *mut EdjeObject,
                                             part:
                                                 *const c_char,
                                             cur: EdjeCursor) -> EinaBool;
    pub fn edje_object_part_text_item_list_get(obj: *const EdjeObject,
                                               part:
                                                   *const c_char)
     -> *const EinaList;
    pub fn edje_object_part_swallow(obj: *mut EdjeObject,
                                    part: *const c_char,
                                    obj_swallow: *mut EvasObject)
     -> EinaBool;
    pub fn edje_object_class_get() -> *const EoClass;
    pub fn edje_obj_update_hints_set(update: EinaBool);
    pub fn edje_obj_update_hints_get() -> EinaBool;
    pub fn edje_obj_mirrored_set(rtl: EinaBool);
    pub fn edje_obj_mirrored_get() -> EinaBool;
    pub fn edje_obj_language_set(language: *const c_char);
    pub fn edje_obj_language_get() -> *const c_char;
    pub fn edje_obj_animation_set(on: EinaBool);
    pub fn edje_obj_animation_get() -> EinaBool;
    pub fn edje_obj_play_set(play: EinaBool);
    pub fn edje_obj_play_get() -> EinaBool;
    pub fn edje_obj_perspective_set(ps: *mut EdjePerspective);
    pub fn edje_obj_perspective_get() -> *const EdjePerspective;
    pub fn edje_obj_scale_set(scale: c_double) -> EinaBool;
    pub fn edje_obj_scale_get() -> c_double;
    pub fn edje_obj_base_scale_get() -> c_double;
    pub fn edje_obj_text_change_cb_set(func: Edje_Text_Change_Cb,
                                       data: *mut c_void);
    pub fn edje_obj_part_text_cursor_begin_set(part:
                                                   *const c_char,
                                               cur: EdjeCursor);
    pub fn edje_obj_part_text_cursor_line_end_set(part:
                                                      *const c_char,
                                                  cur: EdjeCursor);
    pub fn edje_obj_text_class_set(text_class: *const c_char,
                                   font: *const c_char,
                                   size: EvasFontSize) -> EinaBool;
    pub fn edje_obj_part_text_cursor_coord_set(part:
                                                   *const c_char,
                                               cur: EdjeCursor,
                                               x: EvasCoord, y: EvasCoord)
     -> EinaBool;
    pub fn edje_obj_part_text_cursor_end_set(part:
                                                 *const c_char,
                                             cur: EdjeCursor);
    pub fn edje_obj_part_text_escaped_set(part: *const c_char,
                                          text: *const c_char)
     -> EinaBool;
    pub fn edje_obj_item_provider_set(func: Edje_Item_Provider_Cb,
                                      data: *mut c_void);
    pub fn edje_obj_part_text_cursor_line_begin_set(part:
                                                        *const c_char,
                                                    cur: EdjeCursor);
    pub fn edje_obj_message_handler_set(func: EdjeMessageHandlerCb,
                                        data: *mut c_void);
    pub fn edje_obj_size_min_get(minw: *mut EvasCoord,
                                 minh: *mut EvasCoord);
    pub fn edje_obj_access_part_list_get() -> *mut EinaList;
    pub fn edje_obj_load_error_get() -> EdjeLoadError;
    pub fn edje_obj_size_max_get(maxw: *mut EvasCoord,
                                 maxh: *mut EvasCoord);
    pub fn edje_obj_transition_duration_factor_set(scale:
                                                       c_double);
    pub fn edje_obj_transition_duration_factor_get()
     -> c_double;
    pub fn edje_obj_part_table_clear(part: *const c_char,
                                     clear: EinaBool) -> EinaBool;
    pub fn edje_obj_part_external_param_type_get(part:
                                                     *const c_char,
                                                 param:
                                                     *const c_char)
     -> EdjeExternalParamType;
    pub fn edje_obj_part_text_select_allow_set(part:
                                                   *const c_char,
                                               allow: EinaBool);
    pub fn edje_obj_part_state_get(part: *const c_char,
                                   val_ret: *mut c_double)
     -> *const c_char;
    pub fn edje_obj_text_markup_filter_callback_del_full(part:
                                                             *const c_char,
                                                         func:
                                                             EdjeMarkupFilterCb,
                                                         data:
                                                             *mut c_void)
     -> *mut c_void;
    pub fn edje_obj_part_drag_step_set(part: *const c_char,
                                       dx: c_double,
                                       dy: c_double)
     -> EinaBool;
    pub fn edje_obj_part_drag_step_get(part: *const c_char,
                                       dx: *mut c_double,
                                       dy: *mut c_double)
     -> EinaBool;
    pub fn edje_obj_part_text_imf_context_get(part:
                                                  *const c_char)
     -> *mut c_void;
    pub fn edje_obj_part_text_select_begin(part:
                                               *const c_char);
    pub fn edje_obj_part_text_style_user_peek(part:
                                                  *const c_char)
     -> *const c_char;
    pub fn edje_obj_signal_callback_del(emission:
                                            *const c_char,
                                        source: *const c_char,
                                        func: EdjeSignalCb,
                                        data: *mut c_void)
     -> *mut c_void;
    pub fn edje_obj_part_text_cursor_next(part: *const c_char,
                                          cur: EdjeCursor) -> EinaBool;
    pub fn edje_obj_part_text_style_user_push(part:
                                                  *const c_char,
                                              style:
                                                  *const c_char);
    pub fn edje_obj_part_text_append(part: *const c_char,
                                     text: *const c_char);
    pub fn edje_obj_part_geometry_get(part: *const c_char,
                                      x: *mut EvasCoord, y: *mut EvasCoord,
                                      w: *mut EvasCoord, h: *mut EvasCoord)
     -> EinaBool;
    pub fn edje_obj_part_text_input_panel_hide(part:
                                                   *const c_char);
    pub fn edje_obj_part_text_item_geometry_get(part:
                                                    *const c_char,
                                                item:
                                                    *const c_char,
                                                cx: *mut EvasCoord,
                                                cy: *mut EvasCoord,
                                                cw: *mut EvasCoord,
                                                ch: *mut EvasCoord)
     -> EinaBool;
    pub fn edje_obj_part_table_unpack(part: *const c_char,
                                      child_obj: *mut EvasObject)
     -> EinaBool;
    pub fn edje_obj_part_text_select_abort(part:
                                               *const c_char);
    pub fn edje_obj_text_insert_filter_callback_del_full(part:
                                                             *const c_char,
                                                         func:
                                                             EdjeTextFilterCb,
                                                         data:
                                                             *mut c_void)
     -> *mut c_void;
    pub fn edje_obj_part_text_style_user_pop(part:
                                                 *const c_char);
    pub fn edje_obj_part_text_input_panel_imdata_set(part:
                                                         *const c_char,
                                                     data:
                                                         *const c_void,
                                                     len:
                                                         c_int);
    pub fn edje_obj_part_text_input_panel_imdata_get(part:
                                                         *const c_char,
                                                     data:
                                                         *mut c_void,
                                                     len:
                                                         *mut c_int);
    pub fn edje_obj_part_text_insert(part: *const c_char,
                                     text: *const c_char);
    pub fn edje_obj_part_box_remove_at(part: *const c_char,
                                       pos: c_uint)
     -> *mut EvasObject;
    pub fn edje_obj_part_text_cursor_copy(part: *const c_char,
                                          src: EdjeCursor, dst: EdjeCursor);
    pub fn edje_obj_parts_extends_calc(x: *mut EvasCoord, y: *mut EvasCoord,
                                       w: *mut EvasCoord, h: *mut EvasCoord)
     -> EinaBool;
    pub fn edje_obj_part_drag_value_set(part: *const c_char,
                                        dx: c_double,
                                        dy: c_double)
     -> EinaBool;
    pub fn edje_obj_part_drag_value_get(part: *const c_char,
                                        dx: *mut c_double,
                                        dy: *mut c_double)
     -> EinaBool;
    pub fn edje_obj_calc_force();
    pub fn edje_obj_part_text_cursor_pos_set(part:
                                                 *const c_char,
                                             cur: EdjeCursor,
                                             pos: c_int);
    pub fn edje_obj_part_text_cursor_pos_get(part:
                                                 *const c_char,
                                             cur: EdjeCursor)
     -> c_int;
    pub fn edje_obj_freeze() -> c_int;
    pub fn edje_obj_part_text_cursor_content_get(part:
                                                     *const c_char,
                                                 cur: EdjeCursor)
     -> *mut c_char;
    pub fn edje_obj_part_text_input_panel_layout_set(part:
                                                         *const c_char,
                                                     layout:
                                                         EdjeInputPanelLayout);
    pub fn edje_obj_part_text_input_panel_layout_get(part:
                                                         *const c_char)
     -> EdjeInputPanelLayout;
    pub fn edje_obj_part_table_pack(part: *const c_char,
                                    child_obj: *mut EvasObject,
                                    col: c_ushort,
                                    row: c_ushort,
                                    colspan: c_ushort,
                                    rowspan: c_ushort)
     -> EinaBool;
    pub fn edje_obj_part_text_input_panel_language_set(part:
                                                           *const c_char,
                                                       lang:
                                                           EdjeInputPanelLang);
    pub fn edje_obj_part_text_input_panel_language_get(part:
                                                           *const c_char)
     -> EdjeInputPanelLang;
    pub fn edje_obj_part_table_col_row_size_get(part:
                                                    *const c_char,
                                                cols:
                                                    *mut c_int,
                                                rows:
                                                    *mut c_int)
     -> EinaBool;
    pub fn edje_obj_part_external_object_get(part:
                                                 *const c_char)
     -> *mut EvasObject;
    pub fn edje_obj_part_external_content_get(part:
                                                  *const c_char,
                                              content:
                                                  *const c_char)
     -> *mut EvasObject;
    pub fn edje_obj_preload(cancel: EinaBool) -> EinaBool;
    pub fn edje_obj_part_text_input_panel_enabled_set(part:
                                                          *const c_char,
                                                      enabled: EinaBool);
    pub fn edje_obj_part_text_input_panel_enabled_get(part:
                                                          *const c_char)
     -> EinaBool;
    pub fn edje_obj_part_text_select_extend(part:
                                                *const c_char);
    pub fn edje_obj_part_box_insert_at(part: *const c_char,
                                       child: *mut EvasObject,
                                       pos: c_uint)
     -> EinaBool;
    pub fn edje_obj_part_text_anchor_geometry_get(part:
                                                      *const c_char,
                                                  anchor:
                                                      *const c_char)
     -> *const EinaList;
    pub fn edje_obj_part_text_cursor_down(part: *const c_char,
                                          cur: EdjeCursor) -> EinaBool;
    pub fn edje_obj_part_drag_page_set(part: *const c_char,
                                       dx: c_double,
                                       dy: c_double)
     -> EinaBool;
    pub fn edje_obj_part_drag_page_get(part: *const c_char,
                                       dx: *mut c_double,
                                       dy: *mut c_double)
     -> EinaBool;
    pub fn edje_obj_part_box_prepend(part: *const c_char,
                                     child: *mut EvasObject) -> EinaBool;
    pub fn edje_obj_signal_emit(emission: *const c_char,
                                source: *const c_char);
    pub fn edje_obj_part_text_input_panel_layout_variation_set(part:
                                                                   *const c_char,
                                                               variation:
                                                                   c_int);
    pub fn edje_obj_part_text_input_panel_layout_variation_get(part:
                                                                   *const c_char)
     -> c_int;
    pub fn edje_obj_message_send(_type: EdjeMessageType,
                                 id: c_int,
                                 msg: *mut c_void);
    pub fn edje_obj_part_text_select_none(part:
                                              *const c_char);
    pub fn edje_obj_part_object_get(part: *const c_char)
     -> *const EvasObject;
    pub fn edje_obj_part_drag_size_set(part: *const c_char,
                                       dw: c_double,
                                       dh: c_double)
     -> EinaBool;
    pub fn edje_obj_part_drag_size_get(part: *const c_char,
                                       dw: *mut c_double,
                                       dh: *mut c_double)
     -> EinaBool;
    pub fn edje_obj_text_insert_filter_callback_del(part:
                                                        *const c_char,
                                                    func: EdjeTextFilterCb)
     -> *mut c_void;
    pub fn edje_obj_part_drag_dir_get(part: *const c_char)
     -> EdjeDragDir;
    pub fn edje_obj_part_text_unescaped_set(part:
                                                *const c_char,
                                            text_to_escape:
                                                *const c_char)
     -> EinaBool;
    pub fn edje_obj_part_text_unescaped_get(part:
                                                *const c_char)
     -> *mut c_char;
    pub fn edje_obj_signal_callback_add(emission:
                                            *const c_char,
                                        source: *const c_char,
                                        func: EdjeSignalCb,
                                        data: *mut c_void);
    pub fn edje_obj_part_text_select_all(part: *const c_char);
    pub fn edje_obj_part_text_input_panel_return_key_disabled_set(part:
                                                                      *const c_char,
                                                                  disabled:
                                                                      EinaBool);
    pub fn edje_obj_part_text_input_panel_return_key_disabled_get(part:
                                                                      *const c_char)
     -> EinaBool;
    pub fn edje_obj_part_text_autocapital_type_set(part:
                                                       *const c_char,
                                                   autocapital_type:
                                                       EdjeTextAutocapitalType);
    pub fn edje_obj_part_text_autocapital_type_get(part:
                                                       *const c_char)
     -> EdjeTextAutocapitalType;
    pub fn edje_obj_part_unswallow(obj_swallow: *mut EvasObject);
    pub fn edje_obj_part_text_prediction_allow_set(part:
                                                       *const c_char,
                                                   prediction: EinaBool);
    pub fn edje_obj_part_text_prediction_allow_get(part:
                                                       *const c_char)
     -> EinaBool;
    pub fn edje_obj_data_get(key: *const c_char)
     -> *const c_char;
    pub fn edje_obj_text_markup_filter_callback_add(part:
                                                        *const c_char,
                                                    func:
                                                        EdjeMarkupFilterCb,
                                                    data:
                                                        *mut c_void);
    pub fn edje_obj_message_signal_process();
    pub fn edje_obj_part_box_remove(part: *const c_char,
                                    child: *mut EvasObject)
     -> *mut EvasObject;
    pub fn edje_obj_thaw() -> c_int;
    pub fn edje_obj_part_swallow_get(part: *const c_char)
     -> *mut EvasObject;
    pub fn edje_obj_part_text_imf_context_reset(part:
                                                    *const c_char);
    pub fn edje_obj_part_text_input_panel_return_key_type_set(part:
                                                                  *const c_char,
                                                              return_key_type:
                                                                  EdjeInputPanelReturnKeyType);
    pub fn edje_obj_part_text_input_panel_return_key_type_get(part:
                                                                  *const c_char)
     -> EdjeInputPanelReturnKeyType;
    pub fn edje_obj_part_table_child_get(part: *const c_char,
                                         col: c_uint,
                                         row: c_uint)
     -> *mut EvasObject;
    pub fn edje_obj_part_box_insert_before(part:
                                               *const c_char,
                                           child: *mut EvasObject,
                                           reference: *const EvasObject)
     -> EinaBool;
    pub fn edje_obj_part_external_param_set(part:
                                                *const c_char,
                                            param: *const EdjeExternalParam)
     -> EinaBool;
    pub fn edje_obj_part_external_param_get(part:
                                                *const c_char,
                                            param: *mut EdjeExternalParam)
     -> EinaBool;
    pub fn edje_obj_size_min_calc(minw: *mut EvasCoord,
                                  minh: *mut EvasCoord);
    pub fn edje_obj_part_box_append(part: *const c_char,
                                    child: *mut EvasObject) -> EinaBool;
    pub fn edje_obj_size_min_restricted_calc(minw: *mut EvasCoord,
                                             minh: *mut EvasCoord,
                                             restrictedw: EvasCoord,
                                             restrictedh: EvasCoord);
    pub fn edje_obj_part_box_remove_all(part: *const c_char,
                                        clear: EinaBool) -> EinaBool;
    pub fn edje_obj_part_drag_page(part: *const c_char,
                                   dx: c_double,
                                   dy: c_double) -> EinaBool;
    pub fn edje_obj_part_text_set(part: *const c_char,
                                  text: *const c_char)
     -> EinaBool;
    pub fn edje_obj_part_text_get(part: *const c_char)
     -> *const c_char;
    pub fn edje_obj_part_text_input_panel_show_on_demand_set(part:
                                                                 *const c_char,
                                                             ondemand:
                                                                 EinaBool);
    pub fn edje_obj_part_text_input_panel_show_on_demand_get(part:
                                                                 *const c_char)
     -> EinaBool;
    pub fn edje_obj_part_text_input_hint_set(part:
                                                 *const c_char,
                                             input_hints: EdjeInputHints);
    pub fn edje_obj_part_text_input_hint_get(part:
                                                 *const c_char)
     -> EdjeInputHints;
    pub fn edje_obj_part_text_selection_get(part:
                                                *const c_char)
     -> *const c_char;
    pub fn edje_obj_part_text_cursor_is_format_get(part:
                                                       *const c_char,
                                                   cur: EdjeCursor)
     -> EinaBool;
    pub fn edje_obj_text_class_get(text_class: *const c_char,
                                   font: *mut *const c_char,
                                   size: *mut EvasFontSize) -> EinaBool;
    pub fn edje_obj_color_class_set(color_class:
                                        *const c_char,
                                    r: c_int,
                                    g: c_int,
                                    b: c_int,
                                    a: c_int,
                                    r2: c_int,
                                    g2: c_int,
                                    b2: c_int,
                                    a2: c_int,
                                    r3: c_int,
                                    g3: c_int,
                                    b3: c_int,
                                    a3: c_int) -> EinaBool;
    pub fn edje_obj_color_class_get(color_class:
                                        *const c_char,
                                    r: *mut c_int,
                                    g: *mut c_int,
                                    b: *mut c_int,
                                    a: *mut c_int,
                                    r2: *mut c_int,
                                    g2: *mut c_int,
                                    b2: *mut c_int,
                                    a2: *mut c_int,
                                    r3: *mut c_int,
                                    g3: *mut c_int,
                                    b3: *mut c_int,
                                    a3: *mut c_int)
     -> EinaBool;
    pub fn edje_obj_color_class_description_get(color_class:
                                                    *const c_char)
     -> *const c_char;
    pub fn edje_obj_part_drag_step(part: *const c_char,
                                   dx: c_double,
                                   dy: c_double) -> EinaBool;
    pub fn edje_obj_part_text_cursor_up(part: *const c_char,
                                        cur: EdjeCursor) -> EinaBool;
    pub fn edje_obj_part_text_cursor_geometry_get(part:
                                                      *const c_char,
                                                  x: *mut EvasCoord,
                                                  y: *mut EvasCoord,
                                                  w: *mut EvasCoord,
                                                  h: *mut EvasCoord);
    pub fn edje_obj_part_text_anchor_list_get(part:
                                                  *const c_char)
     -> *const EinaList;
    pub fn edje_obj_text_insert_filter_callback_add(part:
                                                        *const c_char,
                                                    func: EdjeTextFilterCb,
                                                    data:
                                                        *mut c_void);
    pub fn edje_obj_part_text_input_panel_show(part:
                                                   *const c_char);
    pub fn edje_obj_part_exists(part: *const c_char)
     -> EinaBool;
    pub fn edje_obj_text_markup_filter_callback_del(part:
                                                        *const c_char,
                                                    func:
                                                        EdjeMarkupFilterCb)
     -> *mut c_void;
    pub fn edje_obj_part_text_cursor_is_visible_format_get(part:
                                                               *const c_char,
                                                           cur: EdjeCursor)
     -> EinaBool;
    pub fn edje_obj_part_text_user_insert(part: *const c_char,
                                          text:
                                              *const c_char);
    pub fn edje_obj_part_text_cursor_prev(part: *const c_char,
                                          cur: EdjeCursor) -> EinaBool;
    pub fn edje_obj_part_text_item_list_get(part:
                                                *const c_char)
     -> *const EinaList;
    pub fn edje_obj_part_swallow(part: *const c_char,
                                 obj_swallow: *mut EvasObject) -> EinaBool;
    pub fn edje_edit_class_get() -> *const EoClass;
}
